// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Bluetooth adapter state (DTO for platform channel).
enum BluetoothStateDto {
  unknown,
  unsupported,
  unauthorized,
  off,
  on,
}

/// Connection state (DTO for platform channel).
enum ConnectionStateDto {
  disconnected,
  connecting,
  connected,
  disconnecting,
}

/// Scan configuration (DTO for platform channel).
class ScanConfigDto {
  ScanConfigDto({
    required this.serviceUuids,
    this.timeoutMs,
  });

  /// Service UUIDs to filter by.
  List<String> serviceUuids;

  /// Timeout in milliseconds (null for no timeout).
  int? timeoutMs;

  Object encode() {
    return <Object?>[
      serviceUuids,
      timeoutMs,
    ];
  }

  static ScanConfigDto decode(Object result) {
    result as List<Object?>;
    return ScanConfigDto(
      serviceUuids: (result[0] as List<Object?>?)!.cast<String>(),
      timeoutMs: result[1] as int?,
    );
  }
}

/// Connect configuration (DTO for platform channel).
class ConnectConfigDto {
  ConnectConfigDto({
    this.timeoutMs,
    this.mtu,
  });

  /// Connection timeout in milliseconds.
  int? timeoutMs;

  /// Requested MTU.
  int? mtu;

  Object encode() {
    return <Object?>[
      timeoutMs,
      mtu,
    ];
  }

  static ConnectConfigDto decode(Object result) {
    result as List<Object?>;
    return ConnectConfigDto(
      timeoutMs: result[0] as int?,
      mtu: result[1] as int?,
    );
  }
}

/// A discovered device (DTO for platform channel).
class DeviceDto {
  DeviceDto({
    required this.id,
    this.name,
    required this.rssi,
    required this.serviceUuids,
    this.manufacturerDataCompanyId,
    this.manufacturerData,
  });

  /// Device ID.
  String id;

  /// Device name.
  String? name;

  /// RSSI in dBm.
  int rssi;

  /// Service UUIDs.
  List<String> serviceUuids;

  /// Manufacturer data company ID.
  int? manufacturerDataCompanyId;

  /// Manufacturer data bytes.
  List<int>? manufacturerData;

  Object encode() {
    return <Object?>[
      id,
      name,
      rssi,
      serviceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
    ];
  }

  static DeviceDto decode(Object result) {
    result as List<Object?>;
    return DeviceDto(
      id: result[0]! as String,
      name: result[1] as String?,
      rssi: result[2]! as int,
      serviceUuids: (result[3] as List<Object?>?)!.cast<String>(),
      manufacturerDataCompanyId: result[4] as int?,
      manufacturerData: (result[5] as List<Object?>?)?.cast<int>(),
    );
  }
}

/// Connection state event (DTO for platform channel).
class ConnectionStateEventDto {
  ConnectionStateEventDto({
    required this.deviceId,
    required this.state,
  });

  String deviceId;

  ConnectionStateDto state;

  Object encode() {
    return <Object?>[
      deviceId,
      state,
    ];
  }

  static ConnectionStateEventDto decode(Object result) {
    result as List<Object?>;
    return ConnectionStateEventDto(
      deviceId: result[0]! as String,
      state: result[1]! as ConnectionStateDto,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BluetoothStateDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ConnectionStateDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ScanConfigDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectConfigDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectionStateEventDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BluetoothStateDto.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ConnectionStateDto.values[value];
      case 131: 
        return ScanConfigDto.decode(readValue(buffer)!);
      case 132: 
        return ConnectConfigDto.decode(readValue(buffer)!);
      case 133: 
        return DeviceDto.decode(readValue(buffer)!);
      case 134: 
        return ConnectionStateEventDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API - called from Dart to platform.
class BlueyHostApi {
  /// Constructor for [BlueyHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BlueyHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Get current Bluetooth state.
  Future<BluetoothStateDto> getState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.getState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BluetoothStateDto?)!;
    }
  }

  /// Request to enable Bluetooth.
  /// Returns true if enabled, false if user declined.
  Future<bool> requestEnable() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.requestEnable$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Open system Bluetooth settings.
  Future<void> openSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.openSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start scanning.
  Future<void> startScan(ScanConfigDto config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.startScan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stop scanning.
  Future<void> stopScan() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.stopScan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Connect to a device.
  /// Returns connection handle.
  Future<String> connect(String deviceId, ConnectConfigDto config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[deviceId, config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Disconnect from a device.
  Future<void> disconnect(String deviceId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluey_android.BlueyHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[deviceId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Flutter API - called from platform to Dart.
abstract class BlueyFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Bluetooth state changed.
  void onStateChanged(BluetoothStateDto state);

  /// Device discovered during scan.
  void onDeviceDiscovered(DeviceDto device);

  /// Scan completed or stopped.
  void onScanComplete();

  /// Connection state changed.
  void onConnectionStateChanged(ConnectionStateEventDto event);

  static void setUp(BlueyFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BluetoothStateDto? arg_state = (args[0] as BluetoothStateDto?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onStateChanged was null, expected non-null BluetoothStateDto.');
          try {
            api.onStateChanged(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onDeviceDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onDeviceDiscovered was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceDto? arg_device = (args[0] as DeviceDto?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onDeviceDiscovered was null, expected non-null DeviceDto.');
          try {
            api.onDeviceDiscovered(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onScanComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onScanComplete();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onConnectionStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ConnectionStateEventDto? arg_event = (args[0] as ConnectionStateEventDto?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onConnectionStateChanged was null, expected non-null ConnectionStateEventDto.');
          try {
            api.onConnectionStateChanged(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
