name: bluey
description: A modern, elegant Bluetooth Low Energy library for Flutter
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  bluey_platform_interface:
    path: ../bluey_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
