name: bluey_android
description: Android implementation of Bluey - Bluetooth Low Energy for Flutter
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bluey_platform_interface:
    path: ../bluey_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.0.0

flutter:
  plugin:
    implements: bluey
    platforms:
      android:
        package: com.neutrinographics.bluey
        pluginClass: BlueyPlugin
        dartPluginClass: BlueyAndroid
