name: bluey_ios
description: iOS implementation of Bluey - Bluetooth Low Energy for Flutter
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  bluey_platform_interface:
    path: ../bluey_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  pigeon: ^26.0.4

flutter:
  plugin:
    implements: bluey
    platforms:
      ios:
        pluginClass: BlueyIosPlugin
        dartPluginClass: BlueyIos
