// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Bluetooth adapter state (DTO for platform channel).
enum BluetoothStateDto {
  unknown,
  unsupported,
  unauthorized,
  off,
  on,
}

/// Connection state (DTO for platform channel).
enum ConnectionStateDto {
  disconnected,
  connecting,
  connected,
  disconnecting,
}

/// GATT permission flags (DTO for platform channel).
enum GattPermissionDto {
  read,
  readEncrypted,
  write,
  writeEncrypted,
}

/// GATT status code for responses (DTO for platform channel).
enum GattStatusDto {
  success,
  readNotPermitted,
  writeNotPermitted,
  invalidOffset,
  invalidAttributeLength,
  insufficientAuthentication,
  insufficientEncryption,
  requestNotSupported,
}

/// Severity for a structured log event (DTO for platform channel).
enum LogLevelDto {
  trace,
  debug,
  info,
  warn,
  error,
}

/// Scan configuration (DTO for platform channel).
class ScanConfigDto {
  ScanConfigDto({
    required this.serviceUuids,
    this.timeoutMs,
  });

  /// Service UUIDs to filter by.
  List<String> serviceUuids;

  /// Timeout in milliseconds (null for no timeout).
  int? timeoutMs;

  List<Object?> _toList() {
    return <Object?>[
      serviceUuids,
      timeoutMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanConfigDto decode(Object result) {
    result as List<Object?>;
    return ScanConfigDto(
      serviceUuids: (result[0]! as List<Object?>).cast<String>(),
      timeoutMs: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(timeoutMs, other.timeoutMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Connect configuration (DTO for platform channel).
class ConnectConfigDto {
  ConnectConfigDto({
    this.timeoutMs,
    this.mtu,
  });

  /// Connection timeout in milliseconds.
  int? timeoutMs;

  /// Requested MTU (ignored on iOS - automatically negotiated).
  int? mtu;

  List<Object?> _toList() {
    return <Object?>[
      timeoutMs,
      mtu,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectConfigDto decode(Object result) {
    result as List<Object?>;
    return ConnectConfigDto(
      timeoutMs: result[0] as int?,
      mtu: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeoutMs, other.timeoutMs) && _deepEquals(mtu, other.mtu);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A discovered device (DTO for platform channel).
class DeviceDto {
  DeviceDto({
    required this.id,
    this.name,
    required this.rssi,
    required this.serviceUuids,
    this.manufacturerDataCompanyId,
    this.manufacturerData,
  });

  /// Device ID (UUID on iOS).
  String id;

  /// Device name.
  String? name;

  /// RSSI in dBm.
  int rssi;

  /// Service UUIDs.
  List<String> serviceUuids;

  /// Manufacturer data company ID.
  int? manufacturerDataCompanyId;

  /// Manufacturer data bytes.
  List<int>? manufacturerData;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      rssi,
      serviceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceDto decode(Object result) {
    result as List<Object?>;
    return DeviceDto(
      id: result[0]! as String,
      name: result[1] as String?,
      rssi: result[2]! as int,
      serviceUuids: (result[3]! as List<Object?>).cast<String>(),
      manufacturerDataCompanyId: result[4] as int?,
      manufacturerData: (result[5] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(rssi, other.rssi) && _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(manufacturerDataCompanyId, other.manufacturerDataCompanyId) && _deepEquals(manufacturerData, other.manufacturerData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Connection state event (DTO for platform channel).
class ConnectionStateEventDto {
  ConnectionStateEventDto({
    required this.deviceId,
    required this.state,
  });

  String deviceId;

  ConnectionStateDto state;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectionStateEventDto decode(Object result) {
    result as List<Object?>;
    return ConnectionStateEventDto(
      deviceId: result[0]! as String,
      state: result[1]! as ConnectionStateDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionStateEventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Characteristic properties flags (DTO for platform channel).
class CharacteristicPropertiesDto {
  CharacteristicPropertiesDto({
    required this.canRead,
    required this.canWrite,
    required this.canWriteWithoutResponse,
    required this.canNotify,
    required this.canIndicate,
  });

  bool canRead;

  bool canWrite;

  bool canWriteWithoutResponse;

  bool canNotify;

  bool canIndicate;

  List<Object?> _toList() {
    return <Object?>[
      canRead,
      canWrite,
      canWriteWithoutResponse,
      canNotify,
      canIndicate,
    ];
  }

  Object encode() {
    return _toList();  }

  static CharacteristicPropertiesDto decode(Object result) {
    result as List<Object?>;
    return CharacteristicPropertiesDto(
      canRead: result[0]! as bool,
      canWrite: result[1]! as bool,
      canWriteWithoutResponse: result[2]! as bool,
      canNotify: result[3]! as bool,
      canIndicate: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CharacteristicPropertiesDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(canRead, other.canRead) && _deepEquals(canWrite, other.canWrite) && _deepEquals(canWriteWithoutResponse, other.canWriteWithoutResponse) && _deepEquals(canNotify, other.canNotify) && _deepEquals(canIndicate, other.canIndicate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A descriptor on a remote device (DTO for platform channel).
class DescriptorDto {
  DescriptorDto({
    required this.uuid,
    required this.handle,
  });

  String uuid;

  int handle;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      handle,
    ];
  }

  Object encode() {
    return _toList();  }

  static DescriptorDto decode(Object result) {
    result as List<Object?>;
    return DescriptorDto(
      uuid: result[0]! as String,
      handle: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DescriptorDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(handle, other.handle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A characteristic on a remote device (DTO for platform channel).
class CharacteristicDto {
  CharacteristicDto({
    required this.uuid,
    required this.properties,
    required this.descriptors,
    required this.handle,
  });

  String uuid;

  CharacteristicPropertiesDto properties;

  List<DescriptorDto> descriptors;

  int handle;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      properties,
      descriptors,
      handle,
    ];
  }

  Object encode() {
    return _toList();  }

  static CharacteristicDto decode(Object result) {
    result as List<Object?>;
    return CharacteristicDto(
      uuid: result[0]! as String,
      properties: result[1]! as CharacteristicPropertiesDto,
      descriptors: (result[2]! as List<Object?>).cast<DescriptorDto>(),
      handle: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CharacteristicDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(properties, other.properties) && _deepEquals(descriptors, other.descriptors) && _deepEquals(handle, other.handle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A service on a remote device (DTO for platform channel).
class ServiceDto {
  ServiceDto({
    required this.uuid,
    required this.isPrimary,
    required this.characteristics,
    required this.includedServices,
  });

  String uuid;

  bool isPrimary;

  List<CharacteristicDto> characteristics;

  List<ServiceDto> includedServices;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      isPrimary,
      characteristics,
      includedServices,
    ];
  }

  Object encode() {
    return _toList();  }

  static ServiceDto decode(Object result) {
    result as List<Object?>;
    return ServiceDto(
      uuid: result[0]! as String,
      isPrimary: result[1]! as bool,
      characteristics: (result[2]! as List<Object?>).cast<CharacteristicDto>(),
      includedServices: (result[3]! as List<Object?>).cast<ServiceDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ServiceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(isPrimary, other.isPrimary) && _deepEquals(characteristics, other.characteristics) && _deepEquals(includedServices, other.includedServices);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Notification event (DTO for platform channel).
class NotificationEventDto {
  NotificationEventDto({
    required this.deviceId,
    required this.characteristicUuid,
    required this.value,
  });

  String deviceId;

  String characteristicUuid;

  Uint8List value;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      characteristicUuid,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static NotificationEventDto decode(Object result) {
    result as List<Object?>;
    return NotificationEventDto(
      deviceId: result[0]! as String,
      characteristicUuid: result[1]! as String,
      value: result[2]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationEventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(characteristicUuid, other.characteristicUuid) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// MTU changed event (DTO for platform channel).
class MtuChangedEventDto {
  MtuChangedEventDto({
    required this.deviceId,
    required this.mtu,
  });

  String deviceId;

  int mtu;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      mtu,
    ];
  }

  Object encode() {
    return _toList();  }

  static MtuChangedEventDto decode(Object result) {
    result as List<Object?>;
    return MtuChangedEventDto(
      deviceId: result[0]! as String,
      mtu: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MtuChangedEventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(mtu, other.mtu);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A local descriptor for GATT server (DTO for platform channel).
class LocalDescriptorDto {
  LocalDescriptorDto({
    required this.uuid,
    required this.permissions,
    this.value,
    required this.handle,
  });

  String uuid;

  List<GattPermissionDto> permissions;

  Uint8List? value;

  int handle;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      permissions,
      value,
      handle,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocalDescriptorDto decode(Object result) {
    result as List<Object?>;
    return LocalDescriptorDto(
      uuid: result[0]! as String,
      permissions: (result[1]! as List<Object?>).cast<GattPermissionDto>(),
      value: result[2] as Uint8List?,
      handle: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocalDescriptorDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(permissions, other.permissions) && _deepEquals(value, other.value) && _deepEquals(handle, other.handle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A local characteristic for GATT server (DTO for platform channel).
class LocalCharacteristicDto {
  LocalCharacteristicDto({
    required this.uuid,
    required this.properties,
    required this.permissions,
    required this.descriptors,
    required this.handle,
  });

  String uuid;

  CharacteristicPropertiesDto properties;

  List<GattPermissionDto> permissions;

  List<LocalDescriptorDto> descriptors;

  int handle;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      properties,
      permissions,
      descriptors,
      handle,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocalCharacteristicDto decode(Object result) {
    result as List<Object?>;
    return LocalCharacteristicDto(
      uuid: result[0]! as String,
      properties: result[1]! as CharacteristicPropertiesDto,
      permissions: (result[2]! as List<Object?>).cast<GattPermissionDto>(),
      descriptors: (result[3]! as List<Object?>).cast<LocalDescriptorDto>(),
      handle: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocalCharacteristicDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(properties, other.properties) && _deepEquals(permissions, other.permissions) && _deepEquals(descriptors, other.descriptors) && _deepEquals(handle, other.handle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A local service for GATT server (DTO for platform channel).
class LocalServiceDto {
  LocalServiceDto({
    required this.uuid,
    required this.isPrimary,
    required this.characteristics,
    required this.includedServices,
  });

  String uuid;

  bool isPrimary;

  List<LocalCharacteristicDto> characteristics;

  List<LocalServiceDto> includedServices;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      isPrimary,
      characteristics,
      includedServices,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocalServiceDto decode(Object result) {
    result as List<Object?>;
    return LocalServiceDto(
      uuid: result[0]! as String,
      isPrimary: result[1]! as bool,
      characteristics: (result[2]! as List<Object?>).cast<LocalCharacteristicDto>(),
      includedServices: (result[3]! as List<Object?>).cast<LocalServiceDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocalServiceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(isPrimary, other.isPrimary) && _deepEquals(characteristics, other.characteristics) && _deepEquals(includedServices, other.includedServices);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Advertising configuration (DTO for platform channel).
/// Note: iOS has limited advertising support compared to Android.
/// Only name and serviceUuids are supported; manufacturer data is ignored.
class AdvertiseConfigDto {
  AdvertiseConfigDto({
    this.name,
    required this.serviceUuids,
    this.manufacturerDataCompanyId,
    this.manufacturerData,
    this.timeoutMs,
  });

  String? name;

  List<String> serviceUuids;

  int? manufacturerDataCompanyId;

  Uint8List? manufacturerData;

  int? timeoutMs;

  List<Object?> _toList() {
    return <Object?>[
      name,
      serviceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
      timeoutMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AdvertiseConfigDto decode(Object result) {
    result as List<Object?>;
    return AdvertiseConfigDto(
      name: result[0] as String?,
      serviceUuids: (result[1]! as List<Object?>).cast<String>(),
      manufacturerDataCompanyId: result[2] as int?,
      manufacturerData: result[3] as Uint8List?,
      timeoutMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdvertiseConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(manufacturerDataCompanyId, other.manufacturerDataCompanyId) && _deepEquals(manufacturerData, other.manufacturerData) && _deepEquals(timeoutMs, other.timeoutMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A connected central device (DTO for platform channel).
class CentralDto {
  CentralDto({
    required this.id,
    required this.mtu,
  });

  String id;

  int mtu;

  List<Object?> _toList() {
    return <Object?>[
      id,
      mtu,
    ];
  }

  Object encode() {
    return _toList();  }

  static CentralDto decode(Object result) {
    result as List<Object?>;
    return CentralDto(
      id: result[0]! as String,
      mtu: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CentralDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(mtu, other.mtu);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Read request from a central (DTO for platform channel).
class ReadRequestDto {
  ReadRequestDto({
    required this.requestId,
    required this.centralId,
    required this.characteristicUuid,
    required this.offset,
    required this.characteristicHandle,
  });

  int requestId;

  String centralId;

  String characteristicUuid;

  int offset;

  int characteristicHandle;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      centralId,
      characteristicUuid,
      offset,
      characteristicHandle,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReadRequestDto decode(Object result) {
    result as List<Object?>;
    return ReadRequestDto(
      requestId: result[0]! as int,
      centralId: result[1]! as String,
      characteristicUuid: result[2]! as String,
      offset: result[3]! as int,
      characteristicHandle: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReadRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) && _deepEquals(centralId, other.centralId) && _deepEquals(characteristicUuid, other.characteristicUuid) && _deepEquals(offset, other.offset) && _deepEquals(characteristicHandle, other.characteristicHandle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Write request from a central (DTO for platform channel).
class WriteRequestDto {
  WriteRequestDto({
    required this.requestId,
    required this.centralId,
    required this.characteristicUuid,
    required this.value,
    required this.offset,
    required this.responseNeeded,
    required this.characteristicHandle,
  });

  int requestId;

  String centralId;

  String characteristicUuid;

  Uint8List value;

  int offset;

  bool responseNeeded;

  int characteristicHandle;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      centralId,
      characteristicUuid,
      value,
      offset,
      responseNeeded,
      characteristicHandle,
    ];
  }

  Object encode() {
    return _toList();  }

  static WriteRequestDto decode(Object result) {
    result as List<Object?>;
    return WriteRequestDto(
      requestId: result[0]! as int,
      centralId: result[1]! as String,
      characteristicUuid: result[2]! as String,
      value: result[3]! as Uint8List,
      offset: result[4]! as int,
      responseNeeded: result[5]! as bool,
      characteristicHandle: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WriteRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) && _deepEquals(centralId, other.centralId) && _deepEquals(characteristicUuid, other.characteristicUuid) && _deepEquals(value, other.value) && _deepEquals(offset, other.offset) && _deepEquals(responseNeeded, other.responseNeeded) && _deepEquals(characteristicHandle, other.characteristicHandle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A structured log event emitted by the native platform implementation
/// (DTO for platform channel).
class LogEventDto {
  LogEventDto({
    required this.context,
    required this.level,
    required this.message,
    required this.data,
    this.errorCode,
    required this.timestampMicros,
  });

  /// Coarse subsystem tag (e.g. `"connection"`, `"gatt_client"`).
  String context;

  /// Severity of the event.
  LogLevelDto level;

  /// Human-readable message.
  String message;

  /// Optional structured key/value context. Values are nullable to allow
  /// callers to mix scalar types without forcing stringification at the
  /// call site.
  Map<String?, Object?> data;

  /// Optional stable error code (e.g. `"GATT_133"`).
  String? errorCode;

  /// When the event was produced, as microseconds since Unix epoch.
  int timestampMicros;

  List<Object?> _toList() {
    return <Object?>[
      context,
      level,
      message,
      data,
      errorCode,
      timestampMicros,
    ];
  }

  Object encode() {
    return _toList();  }

  static LogEventDto decode(Object result) {
    result as List<Object?>;
    return LogEventDto(
      context: result[0]! as String,
      level: result[1]! as LogLevelDto,
      message: result[2]! as String,
      data: (result[3]! as Map<Object?, Object?>).cast<String?, Object?>(),
      errorCode: result[4] as String?,
      timestampMicros: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LogEventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(context, other.context) && _deepEquals(level, other.level) && _deepEquals(message, other.message) && _deepEquals(data, other.data) && _deepEquals(errorCode, other.errorCode) && _deepEquals(timestampMicros, other.timestampMicros);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Configuration options for the Bluey plugin.
/// Note: Most options are Android-specific and ignored on iOS.
class BlueyConfigDto {
  BlueyConfigDto({
    required this.cleanupOnActivityDestroy,
    this.discoverServicesTimeoutMs,
    this.readCharacteristicTimeoutMs,
    this.writeCharacteristicTimeoutMs,
    this.readDescriptorTimeoutMs,
    this.writeDescriptorTimeoutMs,
    this.readRssiTimeoutMs,
  });

  /// Ignored on iOS (cleanup is handled automatically by the OS).
  bool cleanupOnActivityDestroy;

  int? discoverServicesTimeoutMs;

  int? readCharacteristicTimeoutMs;

  int? writeCharacteristicTimeoutMs;

  int? readDescriptorTimeoutMs;

  int? writeDescriptorTimeoutMs;

  int? readRssiTimeoutMs;

  List<Object?> _toList() {
    return <Object?>[
      cleanupOnActivityDestroy,
      discoverServicesTimeoutMs,
      readCharacteristicTimeoutMs,
      writeCharacteristicTimeoutMs,
      readDescriptorTimeoutMs,
      writeDescriptorTimeoutMs,
      readRssiTimeoutMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static BlueyConfigDto decode(Object result) {
    result as List<Object?>;
    return BlueyConfigDto(
      cleanupOnActivityDestroy: result[0]! as bool,
      discoverServicesTimeoutMs: result[1] as int?,
      readCharacteristicTimeoutMs: result[2] as int?,
      writeCharacteristicTimeoutMs: result[3] as int?,
      readDescriptorTimeoutMs: result[4] as int?,
      writeDescriptorTimeoutMs: result[5] as int?,
      readRssiTimeoutMs: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BlueyConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(cleanupOnActivityDestroy, other.cleanupOnActivityDestroy) && _deepEquals(discoverServicesTimeoutMs, other.discoverServicesTimeoutMs) && _deepEquals(readCharacteristicTimeoutMs, other.readCharacteristicTimeoutMs) && _deepEquals(writeCharacteristicTimeoutMs, other.writeCharacteristicTimeoutMs) && _deepEquals(readDescriptorTimeoutMs, other.readDescriptorTimeoutMs) && _deepEquals(writeDescriptorTimeoutMs, other.writeDescriptorTimeoutMs) && _deepEquals(readRssiTimeoutMs, other.readRssiTimeoutMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BluetoothStateDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ConnectionStateDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is GattPermissionDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is GattStatusDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is LogLevelDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is ScanConfigDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectConfigDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectionStateEventDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is CharacteristicPropertiesDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is DescriptorDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is CharacteristicDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is ServiceDto) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is NotificationEventDto) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is MtuChangedEventDto) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is LocalDescriptorDto) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is LocalCharacteristicDto) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is LocalServiceDto) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is AdvertiseConfigDto) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is CentralDto) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is ReadRequestDto) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is WriteRequestDto) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is LogEventDto) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is BlueyConfigDto) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BluetoothStateDto.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConnectionStateDto.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : GattPermissionDto.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : GattStatusDto.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : LogLevelDto.values[value];
      case 134:
        return ScanConfigDto.decode(readValue(buffer)!);
      case 135:
        return ConnectConfigDto.decode(readValue(buffer)!);
      case 136:
        return DeviceDto.decode(readValue(buffer)!);
      case 137:
        return ConnectionStateEventDto.decode(readValue(buffer)!);
      case 138:
        return CharacteristicPropertiesDto.decode(readValue(buffer)!);
      case 139:
        return DescriptorDto.decode(readValue(buffer)!);
      case 140:
        return CharacteristicDto.decode(readValue(buffer)!);
      case 141:
        return ServiceDto.decode(readValue(buffer)!);
      case 142:
        return NotificationEventDto.decode(readValue(buffer)!);
      case 143:
        return MtuChangedEventDto.decode(readValue(buffer)!);
      case 144:
        return LocalDescriptorDto.decode(readValue(buffer)!);
      case 145:
        return LocalCharacteristicDto.decode(readValue(buffer)!);
      case 146:
        return LocalServiceDto.decode(readValue(buffer)!);
      case 147:
        return AdvertiseConfigDto.decode(readValue(buffer)!);
      case 148:
        return CentralDto.decode(readValue(buffer)!);
      case 149:
        return ReadRequestDto.decode(readValue(buffer)!);
      case 150:
        return WriteRequestDto.decode(readValue(buffer)!);
      case 151:
        return LogEventDto.decode(readValue(buffer)!);
      case 152:
        return BlueyConfigDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API - called from Dart to platform (iOS).
class BlueyHostApi {
  /// Constructor for [BlueyHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BlueyHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Configure the Bluey plugin behavior.
  Future<void> configure(BlueyConfigDto config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Get current Bluetooth state.
  Future<BluetoothStateDto> getState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.getState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothStateDto;
  }

  /// Request Bluetooth permissions from the user.
  /// Returns true if all required permissions were granted, false otherwise.
  Future<bool> authorize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.authorize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Open system Bluetooth settings.
  Future<void> openSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.openSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Start scanning.
  Future<void> startScan(ScanConfigDto config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Stop scanning.
  Future<void> stopScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Connect to a device.
  /// Returns connection handle.
  Future<String> connect(String deviceId, ConnectConfigDto config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// Disconnect from a device.
  Future<void> disconnect(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Discover services on a connected device.
  Future<List<ServiceDto>> discoverServices(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ServiceDto>();
  }

  /// Read a characteristic value by platform-minted handle.
  Future<Uint8List> readCharacteristic(String deviceId, int characteristicHandle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.readCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, characteristicHandle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Write a characteristic value by platform-minted handle.
  Future<void> writeCharacteristic(String deviceId, int characteristicHandle, Uint8List value, bool withResponse) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.writeCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, characteristicHandle, value, withResponse]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Enable or disable notifications for a characteristic by handle.
  Future<void> setNotification(String deviceId, int characteristicHandle, bool enable) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.setNotification$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, characteristicHandle, enable]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Read a descriptor value by platform-minted handle.
  Future<Uint8List> readDescriptor(String deviceId, int characteristicHandle, int descriptorHandle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.readDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, characteristicHandle, descriptorHandle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Write a descriptor value by platform-minted handle.
  Future<void> writeDescriptor(String deviceId, int characteristicHandle, int descriptorHandle, Uint8List value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.writeDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, characteristicHandle, descriptorHandle, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Get the maximum write length for a characteristic.
  /// iOS automatically negotiates MTU, so this returns the current negotiated value.
  Future<int> getMaximumWriteLength(String deviceId, bool withResponse) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.getMaximumWriteLength$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, withResponse]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Read the current RSSI for a connected device.
  Future<int> readRssi(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.readRssi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Add a service to the GATT server. Returns the service with all
  /// characteristic and descriptor handles populated.
  Future<LocalServiceDto> addService(LocalServiceDto service) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.addService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[service]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as LocalServiceDto;
  }

  /// Remove a service from the GATT server.
  Future<void> removeService(String serviceUuid) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.removeService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuid]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Start advertising.
  Future<void> startAdvertising(AdvertiseConfigDto config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.startAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Stop advertising.
  Future<void> stopAdvertising() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.stopAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Send a notification to all subscribed centrals, addressed by the
  /// platform-minted handle of a local characteristic.
  Future<void> notifyCharacteristic(int characteristicHandle, Uint8List value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.notifyCharacteristic$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[characteristicHandle, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Send a notification to a specific central, addressed by the
  /// platform-minted handle of a local characteristic.
  Future<void> notifyCharacteristicTo(String centralId, int characteristicHandle, Uint8List value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.notifyCharacteristicTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[centralId, characteristicHandle, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Respond to a read request.
  Future<void> respondToReadRequest(int requestId, GattStatusDto status, Uint8List? value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.respondToReadRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, status, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Respond to a write request.
  Future<void> respondToWriteRequest(int requestId, GattStatusDto status) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.respondToWriteRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, status]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Disconnect a central from the server.
  Future<void> disconnectCentral(String centralId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.disconnectCentral$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[centralId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Close the GATT server and disconnect all centrals.
  Future<void> closeServer() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.closeServer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Set the minimum severity level for native log events forwarded to Dart.
  ///
  /// Events strictly below [level] are dropped on the native side before
  /// being marshalled across the platform channel.
  Future<void> setLogLevel(LogLevelDto level) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bluey_ios.BlueyHostApi.setLogLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Flutter API - called from platform to Dart.
abstract class BlueyFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Bluetooth state changed.
  void onStateChanged(BluetoothStateDto state);

  /// Device discovered during scan.
  void onDeviceDiscovered(DeviceDto device);

  /// Scan completed or stopped.
  void onScanComplete();

  /// Connection state changed.
  void onConnectionStateChanged(ConnectionStateEventDto event);

  /// Characteristic notification received.
  void onNotification(NotificationEventDto event);

  /// MTU changed for a connection (iOS reports this after connection).
  void onMtuChanged(MtuChangedEventDto event);

  /// A central device connected to the server.
  void onCentralConnected(CentralDto central);

  /// A central device disconnected from the server.
  void onCentralDisconnected(String centralId);

  /// A read request was received from a central.
  void onReadRequest(ReadRequestDto request);

  /// A write request was received from a central.
  void onWriteRequest(WriteRequestDto request);

  /// A central subscribed to notifications for a characteristic.
  void onCharacteristicSubscribed(String centralId, String characteristicUuid);

  /// A central unsubscribed from notifications for a characteristic.
  void onCharacteristicUnsubscribed(String centralId, String characteristicUuid);

  /// Remote device's GATT services changed (service added/removed on the server).
  void onServicesChanged(String deviceId);

  /// A structured log event was emitted by the native platform.
  void onLog(LogEventDto event);

  static void setUp(BlueyFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final BluetoothStateDto arg_state = args[0]! as BluetoothStateDto;
          try {
            api.onStateChanged(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onDeviceDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final DeviceDto arg_device = args[0]! as DeviceDto;
          try {
            api.onDeviceDiscovered(arg_device);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onScanComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onScanComplete();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ConnectionStateEventDto arg_event = args[0]! as ConnectionStateEventDto;
          try {
            api.onConnectionStateChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onNotification$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NotificationEventDto arg_event = args[0]! as NotificationEventDto;
          try {
            api.onNotification(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onMtuChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final MtuChangedEventDto arg_event = args[0]! as MtuChangedEventDto;
          try {
            api.onMtuChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCentralConnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CentralDto arg_central = args[0]! as CentralDto;
          try {
            api.onCentralConnected(arg_central);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCentralDisconnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_centralId = args[0]! as String;
          try {
            api.onCentralDisconnected(arg_centralId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ReadRequestDto arg_request = args[0]! as ReadRequestDto;
          try {
            api.onReadRequest(arg_request);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onWriteRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WriteRequestDto arg_request = args[0]! as WriteRequestDto;
          try {
            api.onWriteRequest(arg_request);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCharacteristicSubscribed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_centralId = args[0]! as String;
          final String arg_characteristicUuid = args[1]! as String;
          try {
            api.onCharacteristicSubscribed(arg_centralId, arg_characteristicUuid);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCharacteristicUnsubscribed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_centralId = args[0]! as String;
          final String arg_characteristicUuid = args[1]! as String;
          try {
            api.onCharacteristicUnsubscribed(arg_centralId, arg_characteristicUuid);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onServicesChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          try {
            api.onServicesChanged(arg_deviceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onLog$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final LogEventDto arg_event = args[0]! as LogEventDto;
          try {
            api.onLog(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
