// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Bluetooth adapter state (DTO for platform channel).
enum BluetoothStateDto: Int {
  case unknown = 0
  case unsupported = 1
  case unauthorized = 2
  case off = 3
  case on = 4
}

/// Connection state (DTO for platform channel).
enum ConnectionStateDto: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case disconnecting = 3
}

/// GATT permission flags (DTO for platform channel).
enum GattPermissionDto: Int {
  case read = 0
  case readEncrypted = 1
  case write = 2
  case writeEncrypted = 3
}

/// GATT status code for responses (DTO for platform channel).
enum GattStatusDto: Int {
  case success = 0
  case readNotPermitted = 1
  case writeNotPermitted = 2
  case invalidOffset = 3
  case invalidAttributeLength = 4
  case insufficientAuthentication = 5
  case insufficientEncryption = 6
  case requestNotSupported = 7
}

/// Scan configuration (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanConfigDto: Hashable {
  /// Service UUIDs to filter by.
  var serviceUuids: [String]
  /// Timeout in milliseconds (null for no timeout).
  var timeoutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanConfigDto? {
    let serviceUuids = pigeonVar_list[0] as! [String]
    let timeoutMs: Int64? = nilOrValue(pigeonVar_list[1])

    return ScanConfigDto(
      serviceUuids: serviceUuids,
      timeoutMs: timeoutMs
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuids,
      timeoutMs,
    ]
  }
  static func == (lhs: ScanConfigDto, rhs: ScanConfigDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.serviceUuids, rhs.serviceUuids) && deepEqualsMessages(lhs.timeoutMs, rhs.timeoutMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanConfigDto")
    deepHashMessages(value: serviceUuids, hasher: &hasher)
    deepHashMessages(value: timeoutMs, hasher: &hasher)
  }
}

/// Connect configuration (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ConnectConfigDto: Hashable {
  /// Connection timeout in milliseconds.
  var timeoutMs: Int64? = nil
  /// Requested MTU (ignored on iOS - automatically negotiated).
  var mtu: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectConfigDto? {
    let timeoutMs: Int64? = nilOrValue(pigeonVar_list[0])
    let mtu: Int64? = nilOrValue(pigeonVar_list[1])

    return ConnectConfigDto(
      timeoutMs: timeoutMs,
      mtu: mtu
    )
  }
  func toList() -> [Any?] {
    return [
      timeoutMs,
      mtu,
    ]
  }
  static func == (lhs: ConnectConfigDto, rhs: ConnectConfigDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.timeoutMs, rhs.timeoutMs) && deepEqualsMessages(lhs.mtu, rhs.mtu)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectConfigDto")
    deepHashMessages(value: timeoutMs, hasher: &hasher)
    deepHashMessages(value: mtu, hasher: &hasher)
  }
}

/// A discovered device (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceDto: Hashable {
  /// Device ID (UUID on iOS).
  var id: String
  /// Device name.
  var name: String? = nil
  /// RSSI in dBm.
  var rssi: Int64
  /// Service UUIDs.
  var serviceUuids: [String]
  /// Manufacturer data company ID.
  var manufacturerDataCompanyId: Int64? = nil
  /// Manufacturer data bytes.
  var manufacturerData: [Int64]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceDto? {
    let id = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi = pigeonVar_list[2] as! Int64
    let serviceUuids = pigeonVar_list[3] as! [String]
    let manufacturerDataCompanyId: Int64? = nilOrValue(pigeonVar_list[4])
    let manufacturerData: [Int64]? = nilOrValue(pigeonVar_list[5])

    return DeviceDto(
      id: id,
      name: name,
      rssi: rssi,
      serviceUuids: serviceUuids,
      manufacturerDataCompanyId: manufacturerDataCompanyId,
      manufacturerData: manufacturerData
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      rssi,
      serviceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
    ]
  }
  static func == (lhs: DeviceDto, rhs: DeviceDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.rssi, rhs.rssi) && deepEqualsMessages(lhs.serviceUuids, rhs.serviceUuids) && deepEqualsMessages(lhs.manufacturerDataCompanyId, rhs.manufacturerDataCompanyId) && deepEqualsMessages(lhs.manufacturerData, rhs.manufacturerData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeviceDto")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: rssi, hasher: &hasher)
    deepHashMessages(value: serviceUuids, hasher: &hasher)
    deepHashMessages(value: manufacturerDataCompanyId, hasher: &hasher)
    deepHashMessages(value: manufacturerData, hasher: &hasher)
  }
}

/// Connection state event (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionStateEventDto: Hashable {
  var deviceId: String
  var state: ConnectionStateDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionStateEventDto? {
    let deviceId = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! ConnectionStateDto

    return ConnectionStateEventDto(
      deviceId: deviceId,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      state,
    ]
  }
  static func == (lhs: ConnectionStateEventDto, rhs: ConnectionStateEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.deviceId, rhs.deviceId) && deepEqualsMessages(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectionStateEventDto")
    deepHashMessages(value: deviceId, hasher: &hasher)
    deepHashMessages(value: state, hasher: &hasher)
  }
}

/// Characteristic properties flags (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CharacteristicPropertiesDto: Hashable {
  var canRead: Bool
  var canWrite: Bool
  var canWriteWithoutResponse: Bool
  var canNotify: Bool
  var canIndicate: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CharacteristicPropertiesDto? {
    let canRead = pigeonVar_list[0] as! Bool
    let canWrite = pigeonVar_list[1] as! Bool
    let canWriteWithoutResponse = pigeonVar_list[2] as! Bool
    let canNotify = pigeonVar_list[3] as! Bool
    let canIndicate = pigeonVar_list[4] as! Bool

    return CharacteristicPropertiesDto(
      canRead: canRead,
      canWrite: canWrite,
      canWriteWithoutResponse: canWriteWithoutResponse,
      canNotify: canNotify,
      canIndicate: canIndicate
    )
  }
  func toList() -> [Any?] {
    return [
      canRead,
      canWrite,
      canWriteWithoutResponse,
      canNotify,
      canIndicate,
    ]
  }
  static func == (lhs: CharacteristicPropertiesDto, rhs: CharacteristicPropertiesDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.canRead, rhs.canRead) && deepEqualsMessages(lhs.canWrite, rhs.canWrite) && deepEqualsMessages(lhs.canWriteWithoutResponse, rhs.canWriteWithoutResponse) && deepEqualsMessages(lhs.canNotify, rhs.canNotify) && deepEqualsMessages(lhs.canIndicate, rhs.canIndicate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CharacteristicPropertiesDto")
    deepHashMessages(value: canRead, hasher: &hasher)
    deepHashMessages(value: canWrite, hasher: &hasher)
    deepHashMessages(value: canWriteWithoutResponse, hasher: &hasher)
    deepHashMessages(value: canNotify, hasher: &hasher)
    deepHashMessages(value: canIndicate, hasher: &hasher)
  }
}

/// A descriptor on a remote device (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct DescriptorDto: Hashable {
  var uuid: String
  var handle: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DescriptorDto? {
    let uuid = pigeonVar_list[0] as! String
    let handle: Int64? = nilOrValue(pigeonVar_list[1])

    return DescriptorDto(
      uuid: uuid,
      handle: handle
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      handle,
    ]
  }
  static func == (lhs: DescriptorDto, rhs: DescriptorDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.uuid, rhs.uuid) && deepEqualsMessages(lhs.handle, rhs.handle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DescriptorDto")
    deepHashMessages(value: uuid, hasher: &hasher)
    deepHashMessages(value: handle, hasher: &hasher)
  }
}

/// A characteristic on a remote device (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CharacteristicDto: Hashable {
  var uuid: String
  var properties: CharacteristicPropertiesDto
  var descriptors: [DescriptorDto]
  var handle: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CharacteristicDto? {
    let uuid = pigeonVar_list[0] as! String
    let properties = pigeonVar_list[1] as! CharacteristicPropertiesDto
    let descriptors = pigeonVar_list[2] as! [DescriptorDto]
    let handle: Int64? = nilOrValue(pigeonVar_list[3])

    return CharacteristicDto(
      uuid: uuid,
      properties: properties,
      descriptors: descriptors,
      handle: handle
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      properties,
      descriptors,
      handle,
    ]
  }
  static func == (lhs: CharacteristicDto, rhs: CharacteristicDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.uuid, rhs.uuid) && deepEqualsMessages(lhs.properties, rhs.properties) && deepEqualsMessages(lhs.descriptors, rhs.descriptors) && deepEqualsMessages(lhs.handle, rhs.handle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CharacteristicDto")
    deepHashMessages(value: uuid, hasher: &hasher)
    deepHashMessages(value: properties, hasher: &hasher)
    deepHashMessages(value: descriptors, hasher: &hasher)
    deepHashMessages(value: handle, hasher: &hasher)
  }
}

/// A service on a remote device (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ServiceDto: Hashable {
  var uuid: String
  var isPrimary: Bool
  var characteristics: [CharacteristicDto]
  var includedServices: [ServiceDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServiceDto? {
    let uuid = pigeonVar_list[0] as! String
    let isPrimary = pigeonVar_list[1] as! Bool
    let characteristics = pigeonVar_list[2] as! [CharacteristicDto]
    let includedServices = pigeonVar_list[3] as! [ServiceDto]

    return ServiceDto(
      uuid: uuid,
      isPrimary: isPrimary,
      characteristics: characteristics,
      includedServices: includedServices
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      isPrimary,
      characteristics,
      includedServices,
    ]
  }
  static func == (lhs: ServiceDto, rhs: ServiceDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.uuid, rhs.uuid) && deepEqualsMessages(lhs.isPrimary, rhs.isPrimary) && deepEqualsMessages(lhs.characteristics, rhs.characteristics) && deepEqualsMessages(lhs.includedServices, rhs.includedServices)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ServiceDto")
    deepHashMessages(value: uuid, hasher: &hasher)
    deepHashMessages(value: isPrimary, hasher: &hasher)
    deepHashMessages(value: characteristics, hasher: &hasher)
    deepHashMessages(value: includedServices, hasher: &hasher)
  }
}

/// Notification event (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotificationEventDto: Hashable {
  var deviceId: String
  var characteristicUuid: String
  var value: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationEventDto? {
    let deviceId = pigeonVar_list[0] as! String
    let characteristicUuid = pigeonVar_list[1] as! String
    let value = pigeonVar_list[2] as! FlutterStandardTypedData

    return NotificationEventDto(
      deviceId: deviceId,
      characteristicUuid: characteristicUuid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      characteristicUuid,
      value,
    ]
  }
  static func == (lhs: NotificationEventDto, rhs: NotificationEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.deviceId, rhs.deviceId) && deepEqualsMessages(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsMessages(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NotificationEventDto")
    deepHashMessages(value: deviceId, hasher: &hasher)
    deepHashMessages(value: characteristicUuid, hasher: &hasher)
    deepHashMessages(value: value, hasher: &hasher)
  }
}

/// MTU changed event (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct MtuChangedEventDto: Hashable {
  var deviceId: String
  var mtu: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MtuChangedEventDto? {
    let deviceId = pigeonVar_list[0] as! String
    let mtu = pigeonVar_list[1] as! Int64

    return MtuChangedEventDto(
      deviceId: deviceId,
      mtu: mtu
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      mtu,
    ]
  }
  static func == (lhs: MtuChangedEventDto, rhs: MtuChangedEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.deviceId, rhs.deviceId) && deepEqualsMessages(lhs.mtu, rhs.mtu)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MtuChangedEventDto")
    deepHashMessages(value: deviceId, hasher: &hasher)
    deepHashMessages(value: mtu, hasher: &hasher)
  }
}

/// A local descriptor for GATT server (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalDescriptorDto: Hashable {
  var uuid: String
  var permissions: [GattPermissionDto]
  var value: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalDescriptorDto? {
    let uuid = pigeonVar_list[0] as! String
    let permissions = pigeonVar_list[1] as! [GattPermissionDto]
    let value: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return LocalDescriptorDto(
      uuid: uuid,
      permissions: permissions,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      permissions,
      value,
    ]
  }
  static func == (lhs: LocalDescriptorDto, rhs: LocalDescriptorDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.uuid, rhs.uuid) && deepEqualsMessages(lhs.permissions, rhs.permissions) && deepEqualsMessages(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalDescriptorDto")
    deepHashMessages(value: uuid, hasher: &hasher)
    deepHashMessages(value: permissions, hasher: &hasher)
    deepHashMessages(value: value, hasher: &hasher)
  }
}

/// A local characteristic for GATT server (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalCharacteristicDto: Hashable {
  var uuid: String
  var properties: CharacteristicPropertiesDto
  var permissions: [GattPermissionDto]
  var descriptors: [LocalDescriptorDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalCharacteristicDto? {
    let uuid = pigeonVar_list[0] as! String
    let properties = pigeonVar_list[1] as! CharacteristicPropertiesDto
    let permissions = pigeonVar_list[2] as! [GattPermissionDto]
    let descriptors = pigeonVar_list[3] as! [LocalDescriptorDto]

    return LocalCharacteristicDto(
      uuid: uuid,
      properties: properties,
      permissions: permissions,
      descriptors: descriptors
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      properties,
      permissions,
      descriptors,
    ]
  }
  static func == (lhs: LocalCharacteristicDto, rhs: LocalCharacteristicDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.uuid, rhs.uuid) && deepEqualsMessages(lhs.properties, rhs.properties) && deepEqualsMessages(lhs.permissions, rhs.permissions) && deepEqualsMessages(lhs.descriptors, rhs.descriptors)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalCharacteristicDto")
    deepHashMessages(value: uuid, hasher: &hasher)
    deepHashMessages(value: properties, hasher: &hasher)
    deepHashMessages(value: permissions, hasher: &hasher)
    deepHashMessages(value: descriptors, hasher: &hasher)
  }
}

/// A local service for GATT server (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LocalServiceDto: Hashable {
  var uuid: String
  var isPrimary: Bool
  var characteristics: [LocalCharacteristicDto]
  var includedServices: [LocalServiceDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalServiceDto? {
    let uuid = pigeonVar_list[0] as! String
    let isPrimary = pigeonVar_list[1] as! Bool
    let characteristics = pigeonVar_list[2] as! [LocalCharacteristicDto]
    let includedServices = pigeonVar_list[3] as! [LocalServiceDto]

    return LocalServiceDto(
      uuid: uuid,
      isPrimary: isPrimary,
      characteristics: characteristics,
      includedServices: includedServices
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      isPrimary,
      characteristics,
      includedServices,
    ]
  }
  static func == (lhs: LocalServiceDto, rhs: LocalServiceDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.uuid, rhs.uuid) && deepEqualsMessages(lhs.isPrimary, rhs.isPrimary) && deepEqualsMessages(lhs.characteristics, rhs.characteristics) && deepEqualsMessages(lhs.includedServices, rhs.includedServices)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalServiceDto")
    deepHashMessages(value: uuid, hasher: &hasher)
    deepHashMessages(value: isPrimary, hasher: &hasher)
    deepHashMessages(value: characteristics, hasher: &hasher)
    deepHashMessages(value: includedServices, hasher: &hasher)
  }
}

/// Advertising configuration (DTO for platform channel).
/// Note: iOS has limited advertising support compared to Android.
/// Only name and serviceUuids are supported; manufacturer data is ignored.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AdvertiseConfigDto: Hashable {
  var name: String? = nil
  var serviceUuids: [String]
  var manufacturerDataCompanyId: Int64? = nil
  var manufacturerData: FlutterStandardTypedData? = nil
  var timeoutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdvertiseConfigDto? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let serviceUuids = pigeonVar_list[1] as! [String]
    let manufacturerDataCompanyId: Int64? = nilOrValue(pigeonVar_list[2])
    let manufacturerData: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])
    let timeoutMs: Int64? = nilOrValue(pigeonVar_list[4])

    return AdvertiseConfigDto(
      name: name,
      serviceUuids: serviceUuids,
      manufacturerDataCompanyId: manufacturerDataCompanyId,
      manufacturerData: manufacturerData,
      timeoutMs: timeoutMs
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      serviceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
      timeoutMs,
    ]
  }
  static func == (lhs: AdvertiseConfigDto, rhs: AdvertiseConfigDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.serviceUuids, rhs.serviceUuids) && deepEqualsMessages(lhs.manufacturerDataCompanyId, rhs.manufacturerDataCompanyId) && deepEqualsMessages(lhs.manufacturerData, rhs.manufacturerData) && deepEqualsMessages(lhs.timeoutMs, rhs.timeoutMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AdvertiseConfigDto")
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: serviceUuids, hasher: &hasher)
    deepHashMessages(value: manufacturerDataCompanyId, hasher: &hasher)
    deepHashMessages(value: manufacturerData, hasher: &hasher)
    deepHashMessages(value: timeoutMs, hasher: &hasher)
  }
}

/// A connected central device (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CentralDto: Hashable {
  var id: String
  var mtu: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CentralDto? {
    let id = pigeonVar_list[0] as! String
    let mtu = pigeonVar_list[1] as! Int64

    return CentralDto(
      id: id,
      mtu: mtu
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      mtu,
    ]
  }
  static func == (lhs: CentralDto, rhs: CentralDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.mtu, rhs.mtu)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CentralDto")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: mtu, hasher: &hasher)
  }
}

/// Read request from a central (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ReadRequestDto: Hashable {
  var requestId: Int64
  var centralId: String
  var characteristicUuid: String
  var offset: Int64
  var characteristicHandle: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReadRequestDto? {
    let requestId = pigeonVar_list[0] as! Int64
    let centralId = pigeonVar_list[1] as! String
    let characteristicUuid = pigeonVar_list[2] as! String
    let offset = pigeonVar_list[3] as! Int64
    let characteristicHandle: Int64? = nilOrValue(pigeonVar_list[4])

    return ReadRequestDto(
      requestId: requestId,
      centralId: centralId,
      characteristicUuid: characteristicUuid,
      offset: offset,
      characteristicHandle: characteristicHandle
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      centralId,
      characteristicUuid,
      offset,
      characteristicHandle,
    ]
  }
  static func == (lhs: ReadRequestDto, rhs: ReadRequestDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.requestId, rhs.requestId) && deepEqualsMessages(lhs.centralId, rhs.centralId) && deepEqualsMessages(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsMessages(lhs.offset, rhs.offset) && deepEqualsMessages(lhs.characteristicHandle, rhs.characteristicHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReadRequestDto")
    deepHashMessages(value: requestId, hasher: &hasher)
    deepHashMessages(value: centralId, hasher: &hasher)
    deepHashMessages(value: characteristicUuid, hasher: &hasher)
    deepHashMessages(value: offset, hasher: &hasher)
    deepHashMessages(value: characteristicHandle, hasher: &hasher)
  }
}

/// Write request from a central (DTO for platform channel).
///
/// Generated class from Pigeon that represents data sent in messages.
struct WriteRequestDto: Hashable {
  var requestId: Int64
  var centralId: String
  var characteristicUuid: String
  var value: FlutterStandardTypedData
  var offset: Int64
  var responseNeeded: Bool
  var characteristicHandle: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WriteRequestDto? {
    let requestId = pigeonVar_list[0] as! Int64
    let centralId = pigeonVar_list[1] as! String
    let characteristicUuid = pigeonVar_list[2] as! String
    let value = pigeonVar_list[3] as! FlutterStandardTypedData
    let offset = pigeonVar_list[4] as! Int64
    let responseNeeded = pigeonVar_list[5] as! Bool
    let characteristicHandle: Int64? = nilOrValue(pigeonVar_list[6])

    return WriteRequestDto(
      requestId: requestId,
      centralId: centralId,
      characteristicUuid: characteristicUuid,
      value: value,
      offset: offset,
      responseNeeded: responseNeeded,
      characteristicHandle: characteristicHandle
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      centralId,
      characteristicUuid,
      value,
      offset,
      responseNeeded,
      characteristicHandle,
    ]
  }
  static func == (lhs: WriteRequestDto, rhs: WriteRequestDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.requestId, rhs.requestId) && deepEqualsMessages(lhs.centralId, rhs.centralId) && deepEqualsMessages(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsMessages(lhs.value, rhs.value) && deepEqualsMessages(lhs.offset, rhs.offset) && deepEqualsMessages(lhs.responseNeeded, rhs.responseNeeded) && deepEqualsMessages(lhs.characteristicHandle, rhs.characteristicHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WriteRequestDto")
    deepHashMessages(value: requestId, hasher: &hasher)
    deepHashMessages(value: centralId, hasher: &hasher)
    deepHashMessages(value: characteristicUuid, hasher: &hasher)
    deepHashMessages(value: value, hasher: &hasher)
    deepHashMessages(value: offset, hasher: &hasher)
    deepHashMessages(value: responseNeeded, hasher: &hasher)
    deepHashMessages(value: characteristicHandle, hasher: &hasher)
  }
}

/// Configuration options for the Bluey plugin.
/// Note: Most options are Android-specific and ignored on iOS.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BlueyConfigDto: Hashable {
  /// Ignored on iOS (cleanup is handled automatically by the OS).
  var cleanupOnActivityDestroy: Bool
  var discoverServicesTimeoutMs: Int64? = nil
  var readCharacteristicTimeoutMs: Int64? = nil
  var writeCharacteristicTimeoutMs: Int64? = nil
  var readDescriptorTimeoutMs: Int64? = nil
  var writeDescriptorTimeoutMs: Int64? = nil
  var readRssiTimeoutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BlueyConfigDto? {
    let cleanupOnActivityDestroy = pigeonVar_list[0] as! Bool
    let discoverServicesTimeoutMs: Int64? = nilOrValue(pigeonVar_list[1])
    let readCharacteristicTimeoutMs: Int64? = nilOrValue(pigeonVar_list[2])
    let writeCharacteristicTimeoutMs: Int64? = nilOrValue(pigeonVar_list[3])
    let readDescriptorTimeoutMs: Int64? = nilOrValue(pigeonVar_list[4])
    let writeDescriptorTimeoutMs: Int64? = nilOrValue(pigeonVar_list[5])
    let readRssiTimeoutMs: Int64? = nilOrValue(pigeonVar_list[6])

    return BlueyConfigDto(
      cleanupOnActivityDestroy: cleanupOnActivityDestroy,
      discoverServicesTimeoutMs: discoverServicesTimeoutMs,
      readCharacteristicTimeoutMs: readCharacteristicTimeoutMs,
      writeCharacteristicTimeoutMs: writeCharacteristicTimeoutMs,
      readDescriptorTimeoutMs: readDescriptorTimeoutMs,
      writeDescriptorTimeoutMs: writeDescriptorTimeoutMs,
      readRssiTimeoutMs: readRssiTimeoutMs
    )
  }
  func toList() -> [Any?] {
    return [
      cleanupOnActivityDestroy,
      discoverServicesTimeoutMs,
      readCharacteristicTimeoutMs,
      writeCharacteristicTimeoutMs,
      readDescriptorTimeoutMs,
      writeDescriptorTimeoutMs,
      readRssiTimeoutMs,
    ]
  }
  static func == (lhs: BlueyConfigDto, rhs: BlueyConfigDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.cleanupOnActivityDestroy, rhs.cleanupOnActivityDestroy) && deepEqualsMessages(lhs.discoverServicesTimeoutMs, rhs.discoverServicesTimeoutMs) && deepEqualsMessages(lhs.readCharacteristicTimeoutMs, rhs.readCharacteristicTimeoutMs) && deepEqualsMessages(lhs.writeCharacteristicTimeoutMs, rhs.writeCharacteristicTimeoutMs) && deepEqualsMessages(lhs.readDescriptorTimeoutMs, rhs.readDescriptorTimeoutMs) && deepEqualsMessages(lhs.writeDescriptorTimeoutMs, rhs.writeDescriptorTimeoutMs) && deepEqualsMessages(lhs.readRssiTimeoutMs, rhs.readRssiTimeoutMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BlueyConfigDto")
    deepHashMessages(value: cleanupOnActivityDestroy, hasher: &hasher)
    deepHashMessages(value: discoverServicesTimeoutMs, hasher: &hasher)
    deepHashMessages(value: readCharacteristicTimeoutMs, hasher: &hasher)
    deepHashMessages(value: writeCharacteristicTimeoutMs, hasher: &hasher)
    deepHashMessages(value: readDescriptorTimeoutMs, hasher: &hasher)
    deepHashMessages(value: writeDescriptorTimeoutMs, hasher: &hasher)
    deepHashMessages(value: readRssiTimeoutMs, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BluetoothStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GattPermissionDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GattStatusDto(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return ScanConfigDto.fromList(self.readValue() as! [Any?])
    case 134:
      return ConnectConfigDto.fromList(self.readValue() as! [Any?])
    case 135:
      return DeviceDto.fromList(self.readValue() as! [Any?])
    case 136:
      return ConnectionStateEventDto.fromList(self.readValue() as! [Any?])
    case 137:
      return CharacteristicPropertiesDto.fromList(self.readValue() as! [Any?])
    case 138:
      return DescriptorDto.fromList(self.readValue() as! [Any?])
    case 139:
      return CharacteristicDto.fromList(self.readValue() as! [Any?])
    case 140:
      return ServiceDto.fromList(self.readValue() as! [Any?])
    case 141:
      return NotificationEventDto.fromList(self.readValue() as! [Any?])
    case 142:
      return MtuChangedEventDto.fromList(self.readValue() as! [Any?])
    case 143:
      return LocalDescriptorDto.fromList(self.readValue() as! [Any?])
    case 144:
      return LocalCharacteristicDto.fromList(self.readValue() as! [Any?])
    case 145:
      return LocalServiceDto.fromList(self.readValue() as! [Any?])
    case 146:
      return AdvertiseConfigDto.fromList(self.readValue() as! [Any?])
    case 147:
      return CentralDto.fromList(self.readValue() as! [Any?])
    case 148:
      return ReadRequestDto.fromList(self.readValue() as! [Any?])
    case 149:
      return WriteRequestDto.fromList(self.readValue() as! [Any?])
    case 150:
      return BlueyConfigDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BluetoothStateDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConnectionStateDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? GattPermissionDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? GattStatusDto {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScanConfigDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectConfigDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionStateEventDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicPropertiesDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? DescriptorDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? CharacteristicDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ServiceDto {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationEventDto {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? MtuChangedEventDto {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? LocalDescriptorDto {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? LocalCharacteristicDto {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? LocalServiceDto {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? AdvertiseConfigDto {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? CentralDto {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? ReadRequestDto {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? WriteRequestDto {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? BlueyConfigDto {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API - called from Dart to platform (iOS).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BlueyHostApi {
  /// Configure the Bluey plugin behavior.
  func configure(config: BlueyConfigDto, completion: @escaping (Result<Void, Error>) -> Void)
  /// Get current Bluetooth state.
  func getState(completion: @escaping (Result<BluetoothStateDto, Error>) -> Void)
  /// Request Bluetooth permissions from the user.
  /// Returns true if all required permissions were granted, false otherwise.
  func authorize(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Open system Bluetooth settings.
  func openSettings(completion: @escaping (Result<Void, Error>) -> Void)
  /// Start scanning.
  func startScan(config: ScanConfigDto, completion: @escaping (Result<Void, Error>) -> Void)
  /// Stop scanning.
  func stopScan(completion: @escaping (Result<Void, Error>) -> Void)
  /// Connect to a device.
  /// Returns connection handle.
  func connect(deviceId: String, config: ConnectConfigDto, completion: @escaping (Result<String, Error>) -> Void)
  /// Disconnect from a device.
  func disconnect(deviceId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Discover services on a connected device.
  func discoverServices(deviceId: String, completion: @escaping (Result<[ServiceDto], Error>) -> Void)
  /// Read a characteristic value.
  ///
  /// [characteristicHandle] is the platform-minted handle for the
  /// characteristic. Native receivers prefer it when non-null; otherwise
  /// they fall back to UUID-keyed lookup. Nullable during the additive
  /// interim (D.8); D.13 makes it required and drops the UUID arg.
  func readCharacteristic(deviceId: String, characteristicUuid: String, characteristicHandle: Int64?, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Write a characteristic value.
  func writeCharacteristic(deviceId: String, characteristicUuid: String, value: FlutterStandardTypedData, withResponse: Bool, characteristicHandle: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Enable or disable notifications for a characteristic.
  func setNotification(deviceId: String, characteristicUuid: String, enable: Bool, characteristicHandle: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Read a descriptor value.
  ///
  /// [characteristicHandle] / [descriptorHandle] are the platform-minted
  /// handles for the owning characteristic and the descriptor itself.
  /// Native receivers prefer them when non-null; otherwise they fall
  /// back to UUID-keyed lookup. Nullable during the additive interim.
  func readDescriptor(deviceId: String, descriptorUuid: String, characteristicHandle: Int64?, descriptorHandle: Int64?, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Write a descriptor value.
  func writeDescriptor(deviceId: String, descriptorUuid: String, value: FlutterStandardTypedData, characteristicHandle: Int64?, descriptorHandle: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Get the maximum write length for a characteristic.
  /// iOS automatically negotiates MTU, so this returns the current negotiated value.
  func getMaximumWriteLength(deviceId: String, withResponse: Bool) throws -> Int64
  /// Read the current RSSI for a connected device.
  func readRssi(deviceId: String, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Add a service to the GATT server.
  func addService(service: LocalServiceDto, completion: @escaping (Result<Void, Error>) -> Void)
  /// Remove a service from the GATT server.
  func removeService(serviceUuid: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Start advertising.
  func startAdvertising(config: AdvertiseConfigDto, completion: @escaping (Result<Void, Error>) -> Void)
  /// Stop advertising.
  func stopAdvertising(completion: @escaping (Result<Void, Error>) -> Void)
  /// Send a notification to all subscribed centrals.
  ///
  /// [characteristicHandle] is the platform-minted handle for the
  /// local characteristic. Native receivers prefer it when non-null;
  /// otherwise they fall back to UUID-keyed lookup.
  func notifyCharacteristic(characteristicUuid: String, value: FlutterStandardTypedData, characteristicHandle: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Send a notification to a specific central.
  func notifyCharacteristicTo(centralId: String, characteristicUuid: String, value: FlutterStandardTypedData, characteristicHandle: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Respond to a read request.
  func respondToReadRequest(requestId: Int64, status: GattStatusDto, value: FlutterStandardTypedData?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Respond to a write request.
  func respondToWriteRequest(requestId: Int64, status: GattStatusDto, completion: @escaping (Result<Void, Error>) -> Void)
  /// Disconnect a central from the server.
  func disconnectCentral(centralId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Close the GATT server and disconnect all centrals.
  func closeServer(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BlueyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BlueyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BlueyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Configure the Bluey plugin behavior.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! BlueyConfigDto
        api.configure(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// Get current Bluetooth state.
    let getStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.getState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStateChannel.setMessageHandler { _, reply in
        api.getState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStateChannel.setMessageHandler(nil)
    }
    /// Request Bluetooth permissions from the user.
    /// Returns true if all required permissions were granted, false otherwise.
    let authorizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.authorize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeChannel.setMessageHandler { _, reply in
        api.authorize { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeChannel.setMessageHandler(nil)
    }
    /// Open system Bluetooth settings.
    let openSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.openSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSettingsChannel.setMessageHandler { _, reply in
        api.openSettings { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openSettingsChannel.setMessageHandler(nil)
    }
    /// Start scanning.
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ScanConfigDto
        api.startScan(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    /// Stop scanning.
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        api.stopScan { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    /// Connect to a device.
    /// Returns connection handle.
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let configArg = args[1] as! ConnectConfigDto
        api.connect(deviceId: deviceIdArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    /// Disconnect from a device.
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.disconnect(deviceId: deviceIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    /// Discover services on a connected device.
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.discoverServices(deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    /// Read a characteristic value.
    ///
    /// [characteristicHandle] is the platform-minted handle for the
    /// characteristic. Native receivers prefer it when non-null; otherwise
    /// they fall back to UUID-keyed lookup. Nullable during the additive
    /// interim (D.8); D.13 makes it required and drops the UUID arg.
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.readCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let characteristicUuidArg = args[1] as! String
        let characteristicHandleArg: Int64? = nilOrValue(args[2])
        api.readCharacteristic(deviceId: deviceIdArg, characteristicUuid: characteristicUuidArg, characteristicHandle: characteristicHandleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    /// Write a characteristic value.
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.writeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let characteristicUuidArg = args[1] as! String
        let valueArg = args[2] as! FlutterStandardTypedData
        let withResponseArg = args[3] as! Bool
        let characteristicHandleArg: Int64? = nilOrValue(args[4])
        api.writeCharacteristic(deviceId: deviceIdArg, characteristicUuid: characteristicUuidArg, value: valueArg, withResponse: withResponseArg, characteristicHandle: characteristicHandleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    /// Enable or disable notifications for a characteristic.
    let setNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.setNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let characteristicUuidArg = args[1] as! String
        let enableArg = args[2] as! Bool
        let characteristicHandleArg: Int64? = nilOrValue(args[3])
        api.setNotification(deviceId: deviceIdArg, characteristicUuid: characteristicUuidArg, enable: enableArg, characteristicHandle: characteristicHandleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setNotificationChannel.setMessageHandler(nil)
    }
    /// Read a descriptor value.
    ///
    /// [characteristicHandle] / [descriptorHandle] are the platform-minted
    /// handles for the owning characteristic and the descriptor itself.
    /// Native receivers prefer them when non-null; otherwise they fall
    /// back to UUID-keyed lookup. Nullable during the additive interim.
    let readDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.readDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let descriptorUuidArg = args[1] as! String
        let characteristicHandleArg: Int64? = nilOrValue(args[2])
        let descriptorHandleArg: Int64? = nilOrValue(args[3])
        api.readDescriptor(deviceId: deviceIdArg, descriptorUuid: descriptorUuidArg, characteristicHandle: characteristicHandleArg, descriptorHandle: descriptorHandleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readDescriptorChannel.setMessageHandler(nil)
    }
    /// Write a descriptor value.
    let writeDescriptorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.writeDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let descriptorUuidArg = args[1] as! String
        let valueArg = args[2] as! FlutterStandardTypedData
        let characteristicHandleArg: Int64? = nilOrValue(args[3])
        let descriptorHandleArg: Int64? = nilOrValue(args[4])
        api.writeDescriptor(deviceId: deviceIdArg, descriptorUuid: descriptorUuidArg, value: valueArg, characteristicHandle: characteristicHandleArg, descriptorHandle: descriptorHandleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeDescriptorChannel.setMessageHandler(nil)
    }
    /// Get the maximum write length for a characteristic.
    /// iOS automatically negotiates MTU, so this returns the current negotiated value.
    let getMaximumWriteLengthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.getMaximumWriteLength\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMaximumWriteLengthChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let withResponseArg = args[1] as! Bool
        do {
          let result = try api.getMaximumWriteLength(deviceId: deviceIdArg, withResponse: withResponseArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMaximumWriteLengthChannel.setMessageHandler(nil)
    }
    /// Read the current RSSI for a connected device.
    let readRssiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.readRssi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRssiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.readRssi(deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRssiChannel.setMessageHandler(nil)
    }
    /// Add a service to the GATT server.
    let addServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.addService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addServiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serviceArg = args[0] as! LocalServiceDto
        api.addService(service: serviceArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addServiceChannel.setMessageHandler(nil)
    }
    /// Remove a service from the GATT server.
    let removeServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.removeService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeServiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serviceUuidArg = args[0] as! String
        api.removeService(serviceUuid: serviceUuidArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeServiceChannel.setMessageHandler(nil)
    }
    /// Start advertising.
    let startAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.startAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAdvertisingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! AdvertiseConfigDto
        api.startAdvertising(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAdvertisingChannel.setMessageHandler(nil)
    }
    /// Stop advertising.
    let stopAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.stopAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAdvertisingChannel.setMessageHandler { _, reply in
        api.stopAdvertising { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopAdvertisingChannel.setMessageHandler(nil)
    }
    /// Send a notification to all subscribed centrals.
    ///
    /// [characteristicHandle] is the platform-minted handle for the
    /// local characteristic. Native receivers prefer it when non-null;
    /// otherwise they fall back to UUID-keyed lookup.
    let notifyCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.notifyCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      notifyCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let characteristicUuidArg = args[0] as! String
        let valueArg = args[1] as! FlutterStandardTypedData
        let characteristicHandleArg: Int64? = nilOrValue(args[2])
        api.notifyCharacteristic(characteristicUuid: characteristicUuidArg, value: valueArg, characteristicHandle: characteristicHandleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      notifyCharacteristicChannel.setMessageHandler(nil)
    }
    /// Send a notification to a specific central.
    let notifyCharacteristicToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.notifyCharacteristicTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      notifyCharacteristicToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let centralIdArg = args[0] as! String
        let characteristicUuidArg = args[1] as! String
        let valueArg = args[2] as! FlutterStandardTypedData
        let characteristicHandleArg: Int64? = nilOrValue(args[3])
        api.notifyCharacteristicTo(centralId: centralIdArg, characteristicUuid: characteristicUuidArg, value: valueArg, characteristicHandle: characteristicHandleArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      notifyCharacteristicToChannel.setMessageHandler(nil)
    }
    /// Respond to a read request.
    let respondToReadRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.respondToReadRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondToReadRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let statusArg = args[1] as! GattStatusDto
        let valueArg: FlutterStandardTypedData? = nilOrValue(args[2])
        api.respondToReadRequest(requestId: requestIdArg, status: statusArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondToReadRequestChannel.setMessageHandler(nil)
    }
    /// Respond to a write request.
    let respondToWriteRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.respondToWriteRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondToWriteRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let statusArg = args[1] as! GattStatusDto
        api.respondToWriteRequest(requestId: requestIdArg, status: statusArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondToWriteRequestChannel.setMessageHandler(nil)
    }
    /// Disconnect a central from the server.
    let disconnectCentralChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.disconnectCentral\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectCentralChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let centralIdArg = args[0] as! String
        api.disconnectCentral(centralId: centralIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectCentralChannel.setMessageHandler(nil)
    }
    /// Close the GATT server and disconnect all centrals.
    let closeServerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bluey_ios.BlueyHostApi.closeServer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeServerChannel.setMessageHandler { _, reply in
        api.closeServer { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeServerChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API - called from platform to Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BlueyFlutterApiProtocol {
  /// Bluetooth state changed.
  func onStateChanged(state stateArg: BluetoothStateDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Device discovered during scan.
  func onDeviceDiscovered(device deviceArg: DeviceDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Scan completed or stopped.
  func onScanComplete(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Connection state changed.
  func onConnectionStateChanged(event eventArg: ConnectionStateEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Characteristic notification received.
  func onNotification(event eventArg: NotificationEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// MTU changed for a connection (iOS reports this after connection).
  func onMtuChanged(event eventArg: MtuChangedEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A central device connected to the server.
  func onCentralConnected(central centralArg: CentralDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A central device disconnected from the server.
  func onCentralDisconnected(centralId centralIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A read request was received from a central.
  func onReadRequest(request requestArg: ReadRequestDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A write request was received from a central.
  func onWriteRequest(request requestArg: WriteRequestDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A central subscribed to notifications for a characteristic.
  func onCharacteristicSubscribed(centralId centralIdArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A central unsubscribed from notifications for a characteristic.
  func onCharacteristicUnsubscribed(centralId centralIdArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Remote device's GATT services changed (service added/removed on the server).
  func onServicesChanged(deviceId deviceIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BlueyFlutterApi: BlueyFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Bluetooth state changed.
  func onStateChanged(state stateArg: BluetoothStateDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Device discovered during scan.
  func onDeviceDiscovered(device deviceArg: DeviceDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onDeviceDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Scan completed or stopped.
  func onScanComplete(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onScanComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Connection state changed.
  func onConnectionStateChanged(event eventArg: ConnectionStateEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onConnectionStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Characteristic notification received.
  func onNotification(event eventArg: NotificationEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onNotification\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// MTU changed for a connection (iOS reports this after connection).
  func onMtuChanged(event eventArg: MtuChangedEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onMtuChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A central device connected to the server.
  func onCentralConnected(central centralArg: CentralDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCentralConnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([centralArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A central device disconnected from the server.
  func onCentralDisconnected(centralId centralIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCentralDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([centralIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A read request was received from a central.
  func onReadRequest(request requestArg: ReadRequestDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onReadRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A write request was received from a central.
  func onWriteRequest(request requestArg: WriteRequestDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onWriteRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A central subscribed to notifications for a characteristic.
  func onCharacteristicSubscribed(centralId centralIdArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCharacteristicSubscribed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([centralIdArg, characteristicUuidArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A central unsubscribed from notifications for a characteristic.
  func onCharacteristicUnsubscribed(centralId centralIdArg: String, characteristicUuid characteristicUuidArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onCharacteristicUnsubscribed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([centralIdArg, characteristicUuidArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Remote device's GATT services changed (service added/removed on the server).
  func onServicesChanged(deviceId deviceIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bluey_ios.BlueyFlutterApi.onServicesChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
