// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.neutrinographics.bluey

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Bluetooth adapter state (DTO for platform channel). */
enum class BluetoothStateDto(val raw: Int) {
  UNKNOWN(0),
  UNSUPPORTED(1),
  UNAUTHORIZED(2),
  OFF(3),
  ON(4);

  companion object {
    fun ofRaw(raw: Int): BluetoothStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Connection state (DTO for platform channel). */
enum class ConnectionStateDto(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3);

  companion object {
    fun ofRaw(raw: Int): ConnectionStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** GATT permission flags (DTO for platform channel). */
enum class GattPermissionDto(val raw: Int) {
  READ(0),
  READ_ENCRYPTED(1),
  WRITE(2),
  WRITE_ENCRYPTED(3);

  companion object {
    fun ofRaw(raw: Int): GattPermissionDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Advertising mode for Android.
 *
 * Controls the advertising interval and power consumption.
 * This setting only affects Android - other platforms manage advertising
 * intervals automatically.
 */
enum class AdvertiseModeDto(val raw: Int) {
  /**
   * Lowest power consumption, 1000ms advertising interval.
   * Best for background advertising where quick discovery isn't critical.
   */
  LOW_POWER(0),
  /**
   * Balanced power consumption, 250ms advertising interval.
   * Good default for most use cases.
   */
  BALANCED(1),
  /**
   * Lowest latency, 100ms advertising interval.
   * Fastest discovery but highest power consumption.
   */
  LOW_LATENCY(2);

  companion object {
    fun ofRaw(raw: Int): AdvertiseModeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** GATT status code for responses (DTO for platform channel). */
enum class GattStatusDto(val raw: Int) {
  SUCCESS(0),
  READ_NOT_PERMITTED(1),
  WRITE_NOT_PERMITTED(2),
  INVALID_OFFSET(3),
  INVALID_ATTRIBUTE_LENGTH(4),
  INSUFFICIENT_AUTHENTICATION(5),
  INSUFFICIENT_ENCRYPTION(6),
  REQUEST_NOT_SUPPORTED(7);

  companion object {
    fun ofRaw(raw: Int): GattStatusDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Severity for a structured log event (DTO for platform channel). */
enum class LogLevelDto(val raw: Int) {
  TRACE(0),
  DEBUG(1),
  INFO(2),
  WARN(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): LogLevelDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Scan configuration (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanConfigDto (
  /** Service UUIDs to filter by. */
  val serviceUuids: List<String>,
  /** Timeout in milliseconds (null for no timeout). */
  val timeoutMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanConfigDto {
      val serviceUuids = pigeonVar_list[0] as List<String>
      val timeoutMs = pigeonVar_list[1] as Long?
      return ScanConfigDto(serviceUuids, timeoutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuids,
      timeoutMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanConfigDto
    return MessagesPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && MessagesPigeonUtils.deepEquals(this.timeoutMs, other.timeoutMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeoutMs)
    return result
  }
}

/**
 * Connect configuration (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ConnectConfigDto (
  /** Connection timeout in milliseconds. */
  val timeoutMs: Long? = null,
  /** Requested MTU. */
  val mtu: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectConfigDto {
      val timeoutMs = pigeonVar_list[0] as Long?
      val mtu = pigeonVar_list[1] as Long?
      return ConnectConfigDto(timeoutMs, mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeoutMs,
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectConfigDto
    return MessagesPigeonUtils.deepEquals(this.timeoutMs, other.timeoutMs) && MessagesPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mtu)
    return result
  }
}

/**
 * A discovered device (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceDto (
  /** Device ID. */
  val id: String,
  /** Device name. */
  val name: String? = null,
  /** RSSI in dBm. */
  val rssi: Long,
  /** Service UUIDs. */
  val serviceUuids: List<String>,
  /** Manufacturer data company ID. */
  val manufacturerDataCompanyId: Long? = null,
  /** Manufacturer data bytes. */
  val manufacturerData: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceDto {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long
      val serviceUuids = pigeonVar_list[3] as List<String>
      val manufacturerDataCompanyId = pigeonVar_list[4] as Long?
      val manufacturerData = pigeonVar_list[5] as List<Long>?
      return DeviceDto(id, name, rssi, serviceUuids, manufacturerDataCompanyId, manufacturerData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      rssi,
      serviceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceDto
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.rssi, other.rssi) && MessagesPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && MessagesPigeonUtils.deepEquals(this.manufacturerDataCompanyId, other.manufacturerDataCompanyId) && MessagesPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rssi)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerDataCompanyId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerData)
    return result
  }
}

/**
 * Connection state event (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ConnectionStateEventDto (
  val deviceId: String,
  val state: ConnectionStateDto
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionStateEventDto {
      val deviceId = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as ConnectionStateDto
      return ConnectionStateEventDto(deviceId, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectionStateEventDto
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    return result
  }
}

/**
 * Characteristic properties flags (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CharacteristicPropertiesDto (
  val canRead: Boolean,
  val canWrite: Boolean,
  val canWriteWithoutResponse: Boolean,
  val canNotify: Boolean,
  val canIndicate: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CharacteristicPropertiesDto {
      val canRead = pigeonVar_list[0] as Boolean
      val canWrite = pigeonVar_list[1] as Boolean
      val canWriteWithoutResponse = pigeonVar_list[2] as Boolean
      val canNotify = pigeonVar_list[3] as Boolean
      val canIndicate = pigeonVar_list[4] as Boolean
      return CharacteristicPropertiesDto(canRead, canWrite, canWriteWithoutResponse, canNotify, canIndicate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      canRead,
      canWrite,
      canWriteWithoutResponse,
      canNotify,
      canIndicate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CharacteristicPropertiesDto
    return MessagesPigeonUtils.deepEquals(this.canRead, other.canRead) && MessagesPigeonUtils.deepEquals(this.canWrite, other.canWrite) && MessagesPigeonUtils.deepEquals(this.canWriteWithoutResponse, other.canWriteWithoutResponse) && MessagesPigeonUtils.deepEquals(this.canNotify, other.canNotify) && MessagesPigeonUtils.deepEquals(this.canIndicate, other.canIndicate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canRead)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canWrite)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canWriteWithoutResponse)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canNotify)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canIndicate)
    return result
  }
}

/**
 * A descriptor on a remote device (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DescriptorDto (
  val uuid: String,
  val handle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DescriptorDto {
      val uuid = pigeonVar_list[0] as String
      val handle = pigeonVar_list[1] as Long
      return DescriptorDto(uuid, handle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      handle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DescriptorDto
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.handle, other.handle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handle)
    return result
  }
}

/**
 * A characteristic on a remote device (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CharacteristicDto (
  val uuid: String,
  val properties: CharacteristicPropertiesDto,
  val descriptors: List<DescriptorDto>,
  val handle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CharacteristicDto {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as CharacteristicPropertiesDto
      val descriptors = pigeonVar_list[2] as List<DescriptorDto>
      val handle = pigeonVar_list[3] as Long
      return CharacteristicDto(uuid, properties, descriptors, handle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      descriptors,
      handle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CharacteristicDto
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.properties, other.properties) && MessagesPigeonUtils.deepEquals(this.descriptors, other.descriptors) && MessagesPigeonUtils.deepEquals(this.handle, other.handle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.properties)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.descriptors)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handle)
    return result
  }
}

/**
 * A service on a remote device (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ServiceDto (
  val uuid: String,
  val isPrimary: Boolean,
  val characteristics: List<CharacteristicDto>,
  val includedServices: List<ServiceDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ServiceDto {
      val uuid = pigeonVar_list[0] as String
      val isPrimary = pigeonVar_list[1] as Boolean
      val characteristics = pigeonVar_list[2] as List<CharacteristicDto>
      val includedServices = pigeonVar_list[3] as List<ServiceDto>
      return ServiceDto(uuid, isPrimary, characteristics, includedServices)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      isPrimary,
      characteristics,
      includedServices,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ServiceDto
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.isPrimary, other.isPrimary) && MessagesPigeonUtils.deepEquals(this.characteristics, other.characteristics) && MessagesPigeonUtils.deepEquals(this.includedServices, other.includedServices)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristics)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.includedServices)
    return result
  }
}

/**
 * Notification event (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NotificationEventDto (
  val deviceId: String,
  val characteristicUuid: String,
  val value: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationEventDto {
      val deviceId = pigeonVar_list[0] as String
      val characteristicUuid = pigeonVar_list[1] as String
      val value = pigeonVar_list[2] as ByteArray
      return NotificationEventDto(deviceId, characteristicUuid, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      characteristicUuid,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationEventDto
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
}

/**
 * MTU changed event (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MtuChangedEventDto (
  val deviceId: String,
  val mtu: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MtuChangedEventDto {
      val deviceId = pigeonVar_list[0] as String
      val mtu = pigeonVar_list[1] as Long
      return MtuChangedEventDto(deviceId, mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MtuChangedEventDto
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mtu)
    return result
  }
}

/**
 * A local descriptor for GATT server (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalDescriptorDto (
  val uuid: String,
  val permissions: List<GattPermissionDto>,
  val value: ByteArray? = null,
  val handle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalDescriptorDto {
      val uuid = pigeonVar_list[0] as String
      val permissions = pigeonVar_list[1] as List<GattPermissionDto>
      val value = pigeonVar_list[2] as ByteArray?
      val handle = pigeonVar_list[3] as Long
      return LocalDescriptorDto(uuid, permissions, value, handle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      permissions,
      value,
      handle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalDescriptorDto
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.permissions, other.permissions) && MessagesPigeonUtils.deepEquals(this.value, other.value) && MessagesPigeonUtils.deepEquals(this.handle, other.handle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.permissions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handle)
    return result
  }
}

/**
 * A local characteristic for GATT server (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalCharacteristicDto (
  val uuid: String,
  val properties: CharacteristicPropertiesDto,
  val permissions: List<GattPermissionDto>,
  val descriptors: List<LocalDescriptorDto>,
  val handle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalCharacteristicDto {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as CharacteristicPropertiesDto
      val permissions = pigeonVar_list[2] as List<GattPermissionDto>
      val descriptors = pigeonVar_list[3] as List<LocalDescriptorDto>
      val handle = pigeonVar_list[4] as Long
      return LocalCharacteristicDto(uuid, properties, permissions, descriptors, handle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      permissions,
      descriptors,
      handle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalCharacteristicDto
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.properties, other.properties) && MessagesPigeonUtils.deepEquals(this.permissions, other.permissions) && MessagesPigeonUtils.deepEquals(this.descriptors, other.descriptors) && MessagesPigeonUtils.deepEquals(this.handle, other.handle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.properties)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.permissions)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.descriptors)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handle)
    return result
  }
}

/**
 * A local service for GATT server (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LocalServiceDto (
  val uuid: String,
  val isPrimary: Boolean,
  val characteristics: List<LocalCharacteristicDto>,
  val includedServices: List<LocalServiceDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalServiceDto {
      val uuid = pigeonVar_list[0] as String
      val isPrimary = pigeonVar_list[1] as Boolean
      val characteristics = pigeonVar_list[2] as List<LocalCharacteristicDto>
      val includedServices = pigeonVar_list[3] as List<LocalServiceDto>
      return LocalServiceDto(uuid, isPrimary, characteristics, includedServices)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      isPrimary,
      characteristics,
      includedServices,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalServiceDto
    return MessagesPigeonUtils.deepEquals(this.uuid, other.uuid) && MessagesPigeonUtils.deepEquals(this.isPrimary, other.isPrimary) && MessagesPigeonUtils.deepEquals(this.characteristics, other.characteristics) && MessagesPigeonUtils.deepEquals(this.includedServices, other.includedServices)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isPrimary)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristics)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.includedServices)
    return result
  }
}

/**
 * Advertising configuration (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AdvertiseConfigDto (
  val name: String? = null,
  val serviceUuids: List<String>,
  /**
   * Service UUIDs to put in the scan-response packet.
   *
   * See `bluey_platform_interface`'s `PlatformAdvertiseConfig` for the
   * rationale (I313).
   */
  val scanResponseServiceUuids: List<String>,
  val manufacturerDataCompanyId: Long? = null,
  val manufacturerData: ByteArray? = null,
  val timeoutMs: Long? = null,
  /**
   * The advertising mode (Android only).
   *
   * Controls the advertising interval and power consumption.
   * Ignored on platforms other than Android.
   *
   * Defaults to [AdvertiseModeDto.lowLatency] if not specified.
   */
  val mode: AdvertiseModeDto? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdvertiseConfigDto {
      val name = pigeonVar_list[0] as String?
      val serviceUuids = pigeonVar_list[1] as List<String>
      val scanResponseServiceUuids = pigeonVar_list[2] as List<String>
      val manufacturerDataCompanyId = pigeonVar_list[3] as Long?
      val manufacturerData = pigeonVar_list[4] as ByteArray?
      val timeoutMs = pigeonVar_list[5] as Long?
      val mode = pigeonVar_list[6] as AdvertiseModeDto?
      return AdvertiseConfigDto(name, serviceUuids, scanResponseServiceUuids, manufacturerDataCompanyId, manufacturerData, timeoutMs, mode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      serviceUuids,
      scanResponseServiceUuids,
      manufacturerDataCompanyId,
      manufacturerData,
      timeoutMs,
      mode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AdvertiseConfigDto
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && MessagesPigeonUtils.deepEquals(this.scanResponseServiceUuids, other.scanResponseServiceUuids) && MessagesPigeonUtils.deepEquals(this.manufacturerDataCompanyId, other.manufacturerDataCompanyId) && MessagesPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && MessagesPigeonUtils.deepEquals(this.timeoutMs, other.timeoutMs) && MessagesPigeonUtils.deepEquals(this.mode, other.mode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scanResponseServiceUuids)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerDataCompanyId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mode)
    return result
  }
}

/**
 * A connected central device (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CentralDto (
  val id: String,
  val mtu: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CentralDto {
      val id = pigeonVar_list[0] as String
      val mtu = pigeonVar_list[1] as Long
      return CentralDto(id, mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CentralDto
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mtu)
    return result
  }
}

/**
 * Read request from a central (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ReadRequestDto (
  val requestId: Long,
  val centralId: String,
  val characteristicUuid: String,
  val offset: Long,
  val characteristicHandle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReadRequestDto {
      val requestId = pigeonVar_list[0] as Long
      val centralId = pigeonVar_list[1] as String
      val characteristicUuid = pigeonVar_list[2] as String
      val offset = pigeonVar_list[3] as Long
      val characteristicHandle = pigeonVar_list[4] as Long
      return ReadRequestDto(requestId, centralId, characteristicUuid, offset, characteristicHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      centralId,
      characteristicUuid,
      offset,
      characteristicHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ReadRequestDto
    return MessagesPigeonUtils.deepEquals(this.requestId, other.requestId) && MessagesPigeonUtils.deepEquals(this.centralId, other.centralId) && MessagesPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && MessagesPigeonUtils.deepEquals(this.offset, other.offset) && MessagesPigeonUtils.deepEquals(this.characteristicHandle, other.characteristicHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.centralId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.offset)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristicHandle)
    return result
  }
}

/**
 * Write request from a central (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WriteRequestDto (
  val requestId: Long,
  val centralId: String,
  val characteristicUuid: String,
  val value: ByteArray,
  val offset: Long,
  val responseNeeded: Boolean,
  val characteristicHandle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WriteRequestDto {
      val requestId = pigeonVar_list[0] as Long
      val centralId = pigeonVar_list[1] as String
      val characteristicUuid = pigeonVar_list[2] as String
      val value = pigeonVar_list[3] as ByteArray
      val offset = pigeonVar_list[4] as Long
      val responseNeeded = pigeonVar_list[5] as Boolean
      val characteristicHandle = pigeonVar_list[6] as Long
      return WriteRequestDto(requestId, centralId, characteristicUuid, value, offset, responseNeeded, characteristicHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      centralId,
      characteristicUuid,
      value,
      offset,
      responseNeeded,
      characteristicHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WriteRequestDto
    return MessagesPigeonUtils.deepEquals(this.requestId, other.requestId) && MessagesPigeonUtils.deepEquals(this.centralId, other.centralId) && MessagesPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && MessagesPigeonUtils.deepEquals(this.value, other.value) && MessagesPigeonUtils.deepEquals(this.offset, other.offset) && MessagesPigeonUtils.deepEquals(this.responseNeeded, other.responseNeeded) && MessagesPigeonUtils.deepEquals(this.characteristicHandle, other.characteristicHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.centralId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.offset)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.responseNeeded)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristicHandle)
    return result
  }
}

/**
 * A structured log event emitted by the native platform implementation
 * (DTO for platform channel).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LogEventDto (
  /** Coarse subsystem tag (e.g. `"connection"`, `"gatt_client"`). */
  val context: String,
  /** Severity of the event. */
  val level: LogLevelDto,
  /** Human-readable message. */
  val message: String,
  /**
   * Optional structured key/value context. Values are nullable to allow
   * callers to mix scalar types without forcing stringification at the
   * call site.
   */
  val data: Map<String?, Any?>,
  /** Optional stable error code (e.g. `"GATT_133"`). */
  val errorCode: String? = null,
  /** When the event was produced, as microseconds since Unix epoch. */
  val timestampMicros: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LogEventDto {
      val context = pigeonVar_list[0] as String
      val level = pigeonVar_list[1] as LogLevelDto
      val message = pigeonVar_list[2] as String
      val data = pigeonVar_list[3] as Map<String?, Any?>
      val errorCode = pigeonVar_list[4] as String?
      val timestampMicros = pigeonVar_list[5] as Long
      return LogEventDto(context, level, message, data, errorCode, timestampMicros)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      context,
      level,
      message,
      data,
      errorCode,
      timestampMicros,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LogEventDto
    return MessagesPigeonUtils.deepEquals(this.context, other.context) && MessagesPigeonUtils.deepEquals(this.level, other.level) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.data, other.data) && MessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && MessagesPigeonUtils.deepEquals(this.timestampMicros, other.timestampMicros)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.context)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.level)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.data)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timestampMicros)
    return result
  }
}

/**
 * Configuration options for the Bluey plugin.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BlueyConfigDto (
  /**
   * Whether to automatically clean up BLE resources when the activity is destroyed.
   *
   * When enabled (default), the plugin will automatically:
   * - Stop advertising
   * - Close the GATT server
   * - Disconnect all connected centrals
   *
   * This prevents "zombie" BLE connections that persist after the app is closed.
   * Disable this if you want to manage cleanup manually via [BlueyHostApi.closeServer].
   */
  val cleanupOnActivityDestroy: Boolean,
  val discoverServicesTimeoutMs: Long? = null,
  val readCharacteristicTimeoutMs: Long? = null,
  val writeCharacteristicTimeoutMs: Long? = null,
  val readDescriptorTimeoutMs: Long? = null,
  val writeDescriptorTimeoutMs: Long? = null,
  val requestMtuTimeoutMs: Long? = null,
  val readRssiTimeoutMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BlueyConfigDto {
      val cleanupOnActivityDestroy = pigeonVar_list[0] as Boolean
      val discoverServicesTimeoutMs = pigeonVar_list[1] as Long?
      val readCharacteristicTimeoutMs = pigeonVar_list[2] as Long?
      val writeCharacteristicTimeoutMs = pigeonVar_list[3] as Long?
      val readDescriptorTimeoutMs = pigeonVar_list[4] as Long?
      val writeDescriptorTimeoutMs = pigeonVar_list[5] as Long?
      val requestMtuTimeoutMs = pigeonVar_list[6] as Long?
      val readRssiTimeoutMs = pigeonVar_list[7] as Long?
      return BlueyConfigDto(cleanupOnActivityDestroy, discoverServicesTimeoutMs, readCharacteristicTimeoutMs, writeCharacteristicTimeoutMs, readDescriptorTimeoutMs, writeDescriptorTimeoutMs, requestMtuTimeoutMs, readRssiTimeoutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cleanupOnActivityDestroy,
      discoverServicesTimeoutMs,
      readCharacteristicTimeoutMs,
      writeCharacteristicTimeoutMs,
      readDescriptorTimeoutMs,
      writeDescriptorTimeoutMs,
      requestMtuTimeoutMs,
      readRssiTimeoutMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BlueyConfigDto
    return MessagesPigeonUtils.deepEquals(this.cleanupOnActivityDestroy, other.cleanupOnActivityDestroy) && MessagesPigeonUtils.deepEquals(this.discoverServicesTimeoutMs, other.discoverServicesTimeoutMs) && MessagesPigeonUtils.deepEquals(this.readCharacteristicTimeoutMs, other.readCharacteristicTimeoutMs) && MessagesPigeonUtils.deepEquals(this.writeCharacteristicTimeoutMs, other.writeCharacteristicTimeoutMs) && MessagesPigeonUtils.deepEquals(this.readDescriptorTimeoutMs, other.readDescriptorTimeoutMs) && MessagesPigeonUtils.deepEquals(this.writeDescriptorTimeoutMs, other.writeDescriptorTimeoutMs) && MessagesPigeonUtils.deepEquals(this.requestMtuTimeoutMs, other.requestMtuTimeoutMs) && MessagesPigeonUtils.deepEquals(this.readRssiTimeoutMs, other.readRssiTimeoutMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cleanupOnActivityDestroy)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.discoverServicesTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.readCharacteristicTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.writeCharacteristicTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.readDescriptorTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.writeDescriptorTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestMtuTimeoutMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.readRssiTimeoutMs)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BluetoothStateDto.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionStateDto.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GattPermissionDto.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AdvertiseModeDto.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GattStatusDto.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LogLevelDto.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanConfigDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectConfigDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceDto.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionStateEventDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CharacteristicPropertiesDto.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DescriptorDto.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CharacteristicDto.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ServiceDto.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationEventDto.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MtuChangedEventDto.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalDescriptorDto.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalCharacteristicDto.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalServiceDto.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdvertiseConfigDto.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CentralDto.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReadRequestDto.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WriteRequestDto.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LogEventDto.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlueyConfigDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BluetoothStateDto -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ConnectionStateDto -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is GattPermissionDto -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is AdvertiseModeDto -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is GattStatusDto -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is LogLevelDto -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is ScanConfigDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ConnectConfigDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is DeviceDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ConnectionStateEventDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CharacteristicPropertiesDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is DescriptorDto -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CharacteristicDto -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is ServiceDto -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is NotificationEventDto -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is MtuChangedEventDto -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is LocalDescriptorDto -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is LocalCharacteristicDto -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is LocalServiceDto -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is AdvertiseConfigDto -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is CentralDto -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is ReadRequestDto -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is WriteRequestDto -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is LogEventDto -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is BlueyConfigDto -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API - called from Dart to platform.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BlueyHostApi {
  /**
   * Configure the Bluey plugin behavior.
   *
   * Call this early in your app lifecycle to customize plugin behavior.
   * See [BlueyConfigDto] for available options.
   */
  fun configure(config: BlueyConfigDto, callback: (Result<Unit>) -> Unit)
  /** Get current Bluetooth state. */
  fun getState(callback: (Result<BluetoothStateDto>) -> Unit)
  /**
   * Request to enable Bluetooth.
   * Returns true if enabled, false if user declined.
   */
  fun requestEnable(callback: (Result<Boolean>) -> Unit)
  /**
   * Request Bluetooth permissions from the user.
   * Returns true if all required permissions were granted, false otherwise.
   */
  fun authorize(callback: (Result<Boolean>) -> Unit)
  /** Open system Bluetooth settings. */
  fun openSettings(callback: (Result<Unit>) -> Unit)
  /** Start scanning. */
  fun startScan(config: ScanConfigDto, callback: (Result<Unit>) -> Unit)
  /** Stop scanning. */
  fun stopScan(callback: (Result<Unit>) -> Unit)
  /**
   * Connect to a device.
   * Returns connection handle.
   */
  fun connect(deviceId: String, config: ConnectConfigDto, callback: (Result<String>) -> Unit)
  /** Disconnect from a device. */
  fun disconnect(deviceId: String, callback: (Result<Unit>) -> Unit)
  /**
   * Discover services on a connected device.
   * Services are cached after first discovery.
   */
  fun discoverServices(deviceId: String, callback: (Result<List<ServiceDto>>) -> Unit)
  /** Read a characteristic value by platform-minted handle. */
  fun readCharacteristic(deviceId: String, characteristicHandle: Long, callback: (Result<ByteArray>) -> Unit)
  /** Write a characteristic value by platform-minted handle. */
  fun writeCharacteristic(deviceId: String, characteristicHandle: Long, value: ByteArray, withResponse: Boolean, callback: (Result<Unit>) -> Unit)
  /** Enable or disable notifications for a characteristic by handle. */
  fun setNotification(deviceId: String, characteristicHandle: Long, enable: Boolean, callback: (Result<Unit>) -> Unit)
  /** Read a descriptor value by platform-minted handle. */
  fun readDescriptor(deviceId: String, characteristicHandle: Long, descriptorHandle: Long, callback: (Result<ByteArray>) -> Unit)
  /** Write a descriptor value by platform-minted handle. */
  fun writeDescriptor(deviceId: String, characteristicHandle: Long, descriptorHandle: Long, value: ByteArray, callback: (Result<Unit>) -> Unit)
  /**
   * Request a specific MTU.
   * Returns the negotiated MTU.
   */
  fun requestMtu(deviceId: String, mtu: Long, callback: (Result<Long>) -> Unit)
  /** Read the current RSSI for a connected device. */
  fun readRssi(deviceId: String, callback: (Result<Long>) -> Unit)
  /**
   * Add a service to the GATT server. Returns the service with all
   * characteristic and descriptor handles populated.
   */
  fun addService(service: LocalServiceDto, callback: (Result<LocalServiceDto>) -> Unit)
  /** Remove a service from the GATT server. */
  fun removeService(serviceUuid: String, callback: (Result<Unit>) -> Unit)
  /** Start advertising. */
  fun startAdvertising(config: AdvertiseConfigDto, callback: (Result<Unit>) -> Unit)
  /** Stop advertising. */
  fun stopAdvertising(callback: (Result<Unit>) -> Unit)
  /**
   * Send a notification to all subscribed centrals, addressed by the
   * platform-minted handle of a local characteristic.
   */
  fun notifyCharacteristic(characteristicHandle: Long, value: ByteArray, callback: (Result<Unit>) -> Unit)
  /**
   * Send a notification to a specific central, addressed by the
   * platform-minted handle of a local characteristic.
   */
  fun notifyCharacteristicTo(centralId: String, characteristicHandle: Long, value: ByteArray, callback: (Result<Unit>) -> Unit)
  /** Respond to a read request. */
  fun respondToReadRequest(requestId: Long, status: GattStatusDto, value: ByteArray?, callback: (Result<Unit>) -> Unit)
  /** Respond to a write request. */
  fun respondToWriteRequest(requestId: Long, status: GattStatusDto, callback: (Result<Unit>) -> Unit)
  /**
   * Close the GATT server and disconnect all centrals.
   * Call this when the server is no longer needed to release resources
   * and properly terminate BLE connections.
   */
  fun closeServer(callback: (Result<Unit>) -> Unit)
  /**
   * Set the minimum severity level for native log events forwarded to Dart.
   *
   * Events strictly below [level] are dropped on the native side before
   * being marshalled across the platform channel.
   */
  fun setLogLevel(level: LogLevelDto, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BlueyHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `BlueyHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BlueyHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as BlueyConfigDto
            api.configure(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.getState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getState{ result: Result<BluetoothStateDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.requestEnable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestEnable{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.authorize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.authorize{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.openSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openSettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ScanConfigDto
            api.startScan(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopScan{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val configArg = args[1] as ConnectConfigDto
            api.connect(deviceIdArg, configArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.disconnect(deviceIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.discoverServices(deviceIdArg) { result: Result<List<ServiceDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val characteristicHandleArg = args[1] as Long
            api.readCharacteristic(deviceIdArg, characteristicHandleArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val characteristicHandleArg = args[1] as Long
            val valueArg = args[2] as ByteArray
            val withResponseArg = args[3] as Boolean
            api.writeCharacteristic(deviceIdArg, characteristicHandleArg, valueArg, withResponseArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.setNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val characteristicHandleArg = args[1] as Long
            val enableArg = args[2] as Boolean
            api.setNotification(deviceIdArg, characteristicHandleArg, enableArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.readDescriptor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val characteristicHandleArg = args[1] as Long
            val descriptorHandleArg = args[2] as Long
            api.readDescriptor(deviceIdArg, characteristicHandleArg, descriptorHandleArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.writeDescriptor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val characteristicHandleArg = args[1] as Long
            val descriptorHandleArg = args[2] as Long
            val valueArg = args[3] as ByteArray
            api.writeDescriptor(deviceIdArg, characteristicHandleArg, descriptorHandleArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.requestMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val mtuArg = args[1] as Long
            api.requestMtu(deviceIdArg, mtuArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.readRssi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.readRssi(deviceIdArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.addService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceArg = args[0] as LocalServiceDto
            api.addService(serviceArg) { result: Result<LocalServiceDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.removeService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceUuidArg = args[0] as String
            api.removeService(serviceUuidArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.startAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as AdvertiseConfigDto
            api.startAdvertising(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.stopAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopAdvertising{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.notifyCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val characteristicHandleArg = args[0] as Long
            val valueArg = args[1] as ByteArray
            api.notifyCharacteristic(characteristicHandleArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.notifyCharacteristicTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val centralIdArg = args[0] as String
            val characteristicHandleArg = args[1] as Long
            val valueArg = args[2] as ByteArray
            api.notifyCharacteristicTo(centralIdArg, characteristicHandleArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.respondToReadRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val statusArg = args[1] as GattStatusDto
            val valueArg = args[2] as ByteArray?
            api.respondToReadRequest(requestIdArg, statusArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.respondToWriteRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val statusArg = args[1] as GattStatusDto
            api.respondToWriteRequest(requestIdArg, statusArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.closeServer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeServer{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.bluey_android.BlueyHostApi.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as LogLevelDto
            api.setLogLevel(levelArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API - called from platform to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class BlueyFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BlueyFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Bluetooth state changed. */
  fun onStateChanged(stateArg: BluetoothStateDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Device discovered during scan. */
  fun onDeviceDiscovered(deviceArg: DeviceDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onDeviceDiscovered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Scan completed or stopped. */
  fun onScanComplete(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onScanComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Connection state changed. */
  fun onConnectionStateChanged(eventArg: ConnectionStateEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onConnectionStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Characteristic notification received. */
  fun onNotification(eventArg: NotificationEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onNotification$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** MTU changed for a connection. */
  fun onMtuChanged(eventArg: MtuChangedEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onMtuChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A central device connected to the server. */
  fun onCentralConnected(centralArg: CentralDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onCentralConnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(centralArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A central device disconnected from the server. */
  fun onCentralDisconnected(centralIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onCentralDisconnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(centralIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A read request was received from a central. */
  fun onReadRequest(requestArg: ReadRequestDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onReadRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A write request was received from a central. */
  fun onWriteRequest(requestArg: WriteRequestDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onWriteRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A central subscribed to notifications for a characteristic. */
  fun onCharacteristicSubscribed(centralIdArg: String, characteristicUuidArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onCharacteristicSubscribed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(centralIdArg, characteristicUuidArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A central unsubscribed from notifications for a characteristic. */
  fun onCharacteristicUnsubscribed(centralIdArg: String, characteristicUuidArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onCharacteristicUnsubscribed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(centralIdArg, characteristicUuidArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Remote device's GATT services changed (service added/removed on the server). */
  fun onServicesChanged(deviceIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onServicesChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** A structured log event was emitted by the native platform. */
  fun onLog(eventArg: LogEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.bluey_android.BlueyFlutterApi.onLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
